"""AST node definitions for the quivers DSL.

The AST is a direct representation of the parsed `.qvr` source. Each
node carries source-location info for error reporting. Recursive sums
use ``dx.TaggedUnion`` with a ``kind`` discriminator: variants subclass
their sum's root and pin ``kind`` to a ``Literal[...]`` value.

This package's submodules group the node families:

* :mod:`._shared` for shared helpers (``AxisSpec``, ``MorphismPrior``)
* :mod:`.types` for type expressions
* :mod:`.spaces` for space expressions
* :mod:`.let_expressions` for let-step arithmetic expressions
* :mod:`.expressions` for value (morphism) expressions
* :mod:`.program_steps` for monadic program steps
* :mod:`.structural` for structural-compression helpers
* :mod:`.declarations` for top-level statements
* :mod:`.module` for the file-level :class:`Module` container

Every public class is re-exported here so ``from quivers.dsl.ast_nodes
import X`` keeps working unchanged.
"""

from quivers.dsl.ast_nodes._shared import (
    AxisSpec,
    CompositionLevel,
    MorphismPrior,
)
from quivers.dsl.ast_nodes.declarations import (
    AliasDecl,
    AlgebraDecl,
    BundleDecl,
    CategoryDecl,
    CompositionRuleEntry,
    ContractionDecl,
    ContractionInput,
    DecoderDecl,
    DeductionDecl,
    DiscretizeDecl,
    EmbedDecl,
    EncoderDecl,
    EnumSetLiteral,
    ExportDecl,
    FreeMonoidExpr,
    FreeResiduatedExpr,
    KernelDecl,
    LetDecl,
    LexiconEntry,
    LossAttachment,
    LossDecl,
    MorphismDecl,
    MorphismParam,
    ObjectDecl,
    ObjectInitializer,
    ObjectParam,
    ProgramDecl,
    ProgramParam,
    RuleDecl,
    ScalarParam,
    SchemaDecl,
    SequentRule,
    SignatureDecl,
    SpaceDecl,
    Statement,
    TypeAliasDecl,
)
from quivers.dsl.ast_nodes.expressions import (
    Expr,
    ExprCap,
    ExprChangeBase,
    ExprChartFold,
    ExprCompose,
    ExprCup,
    ExprCurry,
    ExprDagger,
    ExprFan,
    ExprFreeze,
    ExprFromData,
    ExprIdent,
    ExprIdentity,
    ExprMarginalize,
    ExprMorphismCall,
    ExprParser,
    ExprRepeat,
    ExprScan,
    ExprStack,
    ExprTensorProduct,
    ExprTrace,
    ExprTransCompose,
)
from quivers.dsl.ast_nodes.let_expressions import (
    LetExprBinOp,
    LetExprCall,
    LetExprFactor,
    LetExprIndex,
    LetExprLambda,
    LetExprList,
    LetExprLiteral,
    LetExprMethodCall,
    LetExprNode,
    LetExprString,
    LetExprUnaryOp,
    LetExprVar,
    LetFactorBinder,
    LetFactorCase,
)
from quivers.dsl.ast_nodes.module import Module
from quivers.dsl.ast_nodes.program_steps import (
    BindStep,
    DrawStep,
    GroupedBodyObserveStep,
    GroupedLatentInitStep,
    GroupedObserveEntry,
    LetStep,
    MarginalizeStep,
    PlateDrawStep,
    ProgramStep,
    VectorisedObserveStep,
)
from quivers.dsl.ast_nodes.spaces import (
    SpaceConstructor,
    SpaceExpr,
    SpaceName,
    SpaceProduct,
)
from quivers.dsl.ast_nodes.structural import (
    BinderArg,
    BinderDecl,
    BinderVar,
    ConstructorDecl,
    EdgeKindDecl,
    EncoderInitRule,
    EncoderMessageRule,
    EncoderRule,
    EncoderUpdateRule,
    EncoderVarInit,
    SortDecl,
    SortDim,
    SortVocabLiteral,
    VertexKindDecl,
)
from quivers.dsl.ast_nodes.types import (
    TypeCoproduct,
    TypeEffectApply,
    TypeExpr,
    TypeName,
    TypeProduct,
    TypeSlash,
)


__all__ = [
    "AliasDecl",
    "AlgebraDecl",
    "AxisSpec",
    "BinderArg",
    "BinderDecl",
    "BinderVar",
    "BindStep",
    "BundleDecl",
    "CategoryDecl",
    "CompositionLevel",
    "CompositionRuleEntry",
    "ConstructorDecl",
    "ContractionDecl",
    "ContractionInput",
    "DecoderDecl",
    "DeductionDecl",
    "DiscretizeDecl",
    "DrawStep",
    "EdgeKindDecl",
    "EmbedDecl",
    "EncoderDecl",
    "EncoderInitRule",
    "EncoderMessageRule",
    "EncoderRule",
    "EncoderUpdateRule",
    "EncoderVarInit",
    "EnumSetLiteral",
    "ExportDecl",
    "Expr",
    "ExprCap",
    "ExprChangeBase",
    "ExprChartFold",
    "ExprCompose",
    "ExprCup",
    "ExprCurry",
    "ExprDagger",
    "ExprFan",
    "ExprFreeze",
    "ExprFromData",
    "ExprIdent",
    "ExprIdentity",
    "ExprMarginalize",
    "ExprMorphismCall",
    "ExprParser",
    "ExprRepeat",
    "ExprScan",
    "ExprStack",
    "ExprTensorProduct",
    "ExprTrace",
    "ExprTransCompose",
    "FreeMonoidExpr",
    "FreeResiduatedExpr",
    "GroupedBodyObserveStep",
    "GroupedLatentInitStep",
    "GroupedObserveEntry",
    "KernelDecl",
    "LetDecl",
    "LetExprBinOp",
    "LetExprCall",
    "LetExprFactor",
    "LetExprIndex",
    "LetExprLambda",
    "LetExprList",
    "LetExprLiteral",
    "LetExprMethodCall",
    "LetExprNode",
    "LetExprString",
    "LetExprUnaryOp",
    "LetExprVar",
    "LetFactorBinder",
    "LetFactorCase",
    "LetStep",
    "LexiconEntry",
    "LossAttachment",
    "LossDecl",
    "MarginalizeStep",
    "Module",
    "MorphismDecl",
    "MorphismParam",
    "MorphismPrior",
    "ObjectDecl",
    "ObjectInitializer",
    "ObjectParam",
    "PlateDrawStep",
    "ProgramDecl",
    "ProgramParam",
    "ProgramStep",
    "RuleDecl",
    "ScalarParam",
    "SchemaDecl",
    "SequentRule",
    "SignatureDecl",
    "SortDecl",
    "SortDim",
    "SortVocabLiteral",
    "SpaceConstructor",
    "SpaceDecl",
    "SpaceExpr",
    "SpaceName",
    "SpaceProduct",
    "Statement",
    "TypeAliasDecl",
    "TypeCoproduct",
    "TypeEffectApply",
    "TypeExpr",
    "TypeName",
    "TypeProduct",
    "TypeSlash",
    "VectorisedObserveStep",
    "VertexKindDecl",
]
