"""AST node definitions for the quivers DSL ().

The AST is a direct representation of the parsed ``.qvr`` source. Each
node carries source-location info for error reporting. Recursive sums
use ``dx.TaggedUnion`` with a ``kind`` discriminator: variants subclass
their sum's root and pin ``kind`` to a ``Literal[...]`` value.

This package's submodules group the node families:

* `._shared` for shared helpers (``AxisSpec``,
  ``CompositionLevel``, the option-value tagged union)
* `.types` for type expressions
* `.let_expressions` for let-arith expressions
* `.expressions` for value (morphism) expressions
* `.program_steps` for monadic program steps
* `.structural` for structural-compression helpers
* `.declarations` for top-level statements (sixteen variants)
* `.module` for the file-level `Module` container

Every public class is re-exported here so ``from quivers.dsl.ast_nodes
import X`` keeps working.
"""

from quivers.dsl.ast_nodes._shared import (
    AxisSpec,
    CompositionLevel,
)
from quivers.dsl.ast_nodes.draw_args import (
    DrawArg,
    DrawArgAtom,
    DrawArgList,
    DrawArgMatrix,
    DrawArgName,
    DrawArgScalar,
    atom_to_draw_arg,
    draw_arg_atom_value,
    draw_args_to_wire,
    wire_args_to_draw_args,
)
from quivers.dsl.ast_nodes.declarations import (
    BundleDecl,
    CategoryDecl,
    CompositionDecl,
    CompositionRuleEntry,
    ContractionDecl,
    ContractionInput,
    DecoderDecl,
    DeductionDecl,
    EncoderDecl,
    ExportDecl,
    LetDecl,
    LexiconCategory,
    LexiconCategoryFixed,
    LexiconCategoryRestricted,
    LexiconCategoryWildcard,
    LexiconEntry,
    LossDecl,
    MorphismDecl,
    MorphismInitFamily,
    MorphismParam,
    MorphismRole,
    ObjectParam,
    OptionCall,
    OptionEntry,
    OptionFlag,
    OptionList,
    OptionName,
    OptionNumber,
    OptionString,
    OptionValue,
    ProgramDecl,
    ProgramParam,
    RuleDecl,
    ScalarParam,
    SchemaDecl,
    SchemaParameter,
    SequentRule,
    SignatureDecl,
    Statement,
    ObjectDecl,
    TypeEnumSet,
    TypeFreeMonoid,
    TypeFreeResiduated,
    TypeFromExpr,
    TypeInitializer,
)
from quivers.dsl.ast_nodes.expressions import (
    Expr,
    ExprCap,
    ExprChangeBase,
    ExprChartFold,
    ExprCompose,
    ExprCup,
    ExprCurry,
    ExprDagger,
    ExprFan,
    ExprFreeze,
    ExprFromData,
    ExprIdent,
    ExprIdentity,
    ExprMarginalize,
    ExprMorphismCall,
    ExprParser,
    ExprRepeat,
    ExprScan,
    ExprStack,
    ExprTensorProduct,
    ExprTrace,
    ExprTransCompose,
)
from quivers.dsl.ast_nodes.let_expressions import (
    LetExprBinOp,
    LetExprCall,
    LetExprFactor,
    LetExprIndex,
    LetExprLambda,
    LetExprList,
    LetExprLiteral,
    LetExprMethodCall,
    LetExprNode,
    LetExprString,
    LetExprUnaryOp,
    LetExprVar,
    LetFactorBinder,
    LetFactorCase,
)
from quivers.dsl.ast_nodes.module import Module
from quivers.dsl.ast_nodes.program_steps import (
    BindStep,
    DrawArg,
    DrawArgDist,
    DrawArgIndex,
    DrawArgList,
    DrawArgName,
    DrawArgScalar,
    DrawStep,
    GroupedBodyObserveStep,
    GroupedLatentInitStep,
    GroupedMarginalizeStep,
    GroupedObserveEntry,
    LetStep,
    MarginalizeStep,
    ObserveStep,
    PlateDrawStep,
    ProgramStep,
    ReturnStep,
    SampleStep,
    ScoreStep,
    VectorisedObserveStep,
    _to_draw_arg as atom_to_draw_arg,
)
from quivers.dsl.ast_nodes.structural import (
    BinderArg,
    BinderDecl,
    BinderVar,
    ConstructorDecl,
    EdgeKindDecl,
    EncoderInitRule,
    EncoderMessageRule,
    EncoderRule,
    EncoderUpdateRule,
    EncoderVarInit,
    SortDecl,
    SortDim,
    SortVocabLiteral,
    VertexKindDecl,
)
from quivers.dsl.ast_nodes.objects import (
    ContinuousConstructor,
    DiscreteConstructor,
    ObjectCoproduct,
    ObjectEffectApply,
    ObjectExpr,
    TypeName,
    ObjectProduct,
    ObjectSlash,
)

__all__ = [
    "AxisSpec",
    "BinderArg",
    "BinderDecl",
    "BinderVar",
    "BindStep",
    "DrawArg",
    "DrawArgAtom",
    "DrawArgList",
    "DrawArgMatrix",
    "DrawArgName",
    "DrawArgScalar",
    "atom_to_draw_arg",
    "draw_arg_atom_value",
    "draw_args_to_wire",
    "wire_args_to_draw_args",
    "BundleDecl",
    "CategoryDecl",
    "CompositionDecl",
    "CompositionLevel",
    "CompositionRuleEntry",
    "ConstructorDecl",
    "ContinuousConstructor",
    "ContractionDecl",
    "ContractionInput",
    "DecoderDecl",
    "DeductionDecl",
    "DiscreteConstructor",
    "DrawArg",
    "DrawArgDist",
    "DrawArgIndex",
    "DrawArgList",
    "DrawArgName",
    "DrawArgScalar",
    "DrawStep",
    "atom_to_draw_arg",
    "EdgeKindDecl",
    "EncoderDecl",
    "EncoderInitRule",
    "EncoderMessageRule",
    "EncoderRule",
    "EncoderUpdateRule",
    "EncoderVarInit",
    "ExportDecl",
    "Expr",
    "ExprCap",
    "ExprChangeBase",
    "ExprChartFold",
    "ExprCompose",
    "ExprCup",
    "ExprCurry",
    "ExprDagger",
    "ExprFan",
    "ExprFreeze",
    "ExprFromData",
    "ExprIdent",
    "ExprIdentity",
    "ExprMarginalize",
    "ExprMorphismCall",
    "ExprParser",
    "ExprRepeat",
    "ExprScan",
    "ExprStack",
    "ExprTensorProduct",
    "ExprTrace",
    "ExprTransCompose",
    "GroupedBodyObserveStep",
    "GroupedLatentInitStep",
    "GroupedMarginalizeStep",
    "GroupedObserveEntry",
    "LetDecl",
    "LetExprBinOp",
    "LetExprCall",
    "LetExprFactor",
    "LetExprIndex",
    "LetExprLambda",
    "LetExprList",
    "LetExprLiteral",
    "LetExprMethodCall",
    "LetExprNode",
    "LetExprString",
    "LetExprUnaryOp",
    "LetExprVar",
    "LetFactorBinder",
    "LetFactorCase",
    "LetStep",
    "ScoreStep",
    "LexiconCategory",
    "LexiconCategoryFixed",
    "LexiconCategoryRestricted",
    "LexiconCategoryWildcard",
    "LexiconEntry",
    "LossDecl",
    "MarginalizeStep",
    "Module",
    "MorphismDecl",
    "MorphismInitFamily",
    "MorphismParam",
    "MorphismRole",
    "ObjectParam",
    "ObserveStep",
    "OptionCall",
    "OptionEntry",
    "OptionFlag",
    "OptionList",
    "OptionName",
    "OptionNumber",
    "OptionString",
    "OptionValue",
    "PlateDrawStep",
    "ProgramDecl",
    "ProgramParam",
    "ProgramStep",
    "ReturnStep",
    "RuleDecl",
    "SampleStep",
    "ScalarParam",
    "SchemaDecl",
    "SchemaParameter",
    "SequentRule",
    "SignatureDecl",
    "SortDecl",
    "SortDim",
    "SortVocabLiteral",
    "Statement",
    "ObjectCoproduct",
    "ObjectDecl",
    "ObjectEffectApply",
    "TypeEnumSet",
    "ObjectExpr",
    "TypeFreeMonoid",
    "TypeFreeResiduated",
    "TypeFromExpr",
    "TypeInitializer",
    "TypeName",
    "ObjectProduct",
    "ObjectSlash",
    "VectorisedObserveStep",
    "VertexKindDecl",
]
