"""AST node definitions for the quivers DSL ().

The AST is a direct representation of the parsed ``.qvr`` source. Each
node carries source-location info for error reporting. Recursive sums
use ``dx.TaggedUnion`` with a ``kind`` discriminator: variants subclass
their sum's root and pin ``kind`` to a ``Literal[...]`` value.

This package's submodules group the node families:

* :mod:`._shared` for shared helpers (``AxisSpec``, ``MorphismPrior``,
  ``CompositionLevel``)
* :mod:`.types` for type expressions
* :mod:`.let_expressions` for let-arith expressions
* :mod:`.expressions` for value (morphism) expressions
* :mod:`.program_steps` for monadic program steps
* :mod:`.structural` for structural-compression helpers
* :mod:`.declarations` for top-level statements (sixteen variants)
* :mod:`.module` for the file-level :class:`Module` container

Every public class is re-exported here so ``from quivers.dsl.ast_nodes
import X`` keeps working.
"""

from quivers.dsl.ast_nodes._shared import (
    AxisSpec,
    CompositionLevel,
    MorphismPrior,
)
from quivers.dsl.ast_nodes.declarations import (
    BundleDecl,
    CategoryDecl,
    CompositionDecl,
    CompositionRuleEntry,
    ContractionDecl,
    ContractionInput,
    DecoderDecl,
    DeductionDecl,
    EncoderDecl,
    ExportDecl,
    LetDecl,
    LexiconEntry,
    LossDecl,
    MorphismDecl,
    MorphismInitFamily,
    MorphismParam,
    MorphismRole,
    ObjectParam,
    OptionCall,
    OptionEntry,
    OptionFlag,
    OptionList,
    OptionName,
    OptionNumber,
    OptionString,
    OptionValue,
    ProgramDecl,
    ProgramParam,
    RuleDecl,
    ScalarParam,
    SchemaDecl,
    SchemaParameter,
    SequentRule,
    SignatureDecl,
    Statement,
    TypeDecl,
    TypeEnumSet,
    TypeFreeMonoid,
    TypeFreeResiduated,
    TypeFromExpr,
    TypeInitializer,
)
from quivers.dsl.ast_nodes.expressions import (
    Expr,
    ExprCap,
    ExprChangeBase,
    ExprChartFold,
    ExprCompose,
    ExprCup,
    ExprCurry,
    ExprDagger,
    ExprFan,
    ExprFreeze,
    ExprFromData,
    ExprIdent,
    ExprIdentity,
    ExprMarginalize,
    ExprMorphismCall,
    ExprParser,
    ExprRepeat,
    ExprScan,
    ExprStack,
    ExprTensorProduct,
    ExprTrace,
    ExprTransCompose,
)
from quivers.dsl.ast_nodes.let_expressions import (
    LetExprBinOp,
    LetExprCall,
    LetExprFactor,
    LetExprIndex,
    LetExprLambda,
    LetExprList,
    LetExprLiteral,
    LetExprMethodCall,
    LetExprNode,
    LetExprString,
    LetExprUnaryOp,
    LetExprVar,
    LetFactorBinder,
    LetFactorCase,
)
from quivers.dsl.ast_nodes.module import Module
from quivers.dsl.ast_nodes.program_steps import (
    BindStep,
    DrawStep,
    GroupedBodyObserveStep,
    GroupedLatentInitStep,
    GroupedMarginalizeStep,
    GroupedObserveEntry,
    LetStep,
    MarginalizeStep,
    ObserveStep,
    PlateDrawStep,
    ProgramStep,
    ReturnStep,
    SampleStep,
    VectorisedObserveStep,
)
from quivers.dsl.ast_nodes.structural import (
    BinderArg,
    BinderDecl,
    BinderVar,
    ConstructorDecl,
    EdgeKindDecl,
    EncoderInitRule,
    EncoderMessageRule,
    EncoderRule,
    EncoderUpdateRule,
    EncoderVarInit,
    SortDecl,
    SortDim,
    SortVocabLiteral,
    VertexKindDecl,
)
from quivers.dsl.ast_nodes.types import (
    ContinuousConstructor,
    DiscreteConstructor,
    TypeCoproduct,
    TypeEffectApply,
    TypeExpr,
    TypeName,
    TypeProduct,
    TypeSlash,
)

__all__ = [
    "AxisSpec",
    "BinderArg",
    "BinderDecl",
    "BinderVar",
    "BindStep",
    "BundleDecl",
    "CategoryDecl",
    "CompositionDecl",
    "CompositionLevel",
    "CompositionRuleEntry",
    "ConstructorDecl",
    "ContinuousConstructor",
    "ContractionDecl",
    "ContractionInput",
    "DecoderDecl",
    "DeductionDecl",
    "DiscreteConstructor",
    "DrawStep",
    "EdgeKindDecl",
    "EncoderDecl",
    "EncoderInitRule",
    "EncoderMessageRule",
    "EncoderRule",
    "EncoderUpdateRule",
    "EncoderVarInit",
    "ExportDecl",
    "Expr",
    "ExprCap",
    "ExprChangeBase",
    "ExprChartFold",
    "ExprCompose",
    "ExprCup",
    "ExprCurry",
    "ExprDagger",
    "ExprFan",
    "ExprFreeze",
    "ExprFromData",
    "ExprIdent",
    "ExprIdentity",
    "ExprMarginalize",
    "ExprMorphismCall",
    "ExprParser",
    "ExprRepeat",
    "ExprScan",
    "ExprStack",
    "ExprTensorProduct",
    "ExprTrace",
    "ExprTransCompose",
    "GroupedBodyObserveStep",
    "GroupedLatentInitStep",
    "GroupedMarginalizeStep",
    "GroupedObserveEntry",
    "LetDecl",
    "LetExprBinOp",
    "LetExprCall",
    "LetExprFactor",
    "LetExprIndex",
    "LetExprLambda",
    "LetExprList",
    "LetExprLiteral",
    "LetExprMethodCall",
    "LetExprNode",
    "LetExprString",
    "LetExprUnaryOp",
    "LetExprVar",
    "LetFactorBinder",
    "LetFactorCase",
    "LetStep",
    "LexiconEntry",
    "LossDecl",
    "MarginalizeStep",
    "Module",
    "MorphismDecl",
    "MorphismInitFamily",
    "MorphismParam",
    "MorphismPrior",
    "MorphismRole",
    "ObjectParam",
    "ObserveStep",
    "OptionCall",
    "OptionEntry",
    "OptionFlag",
    "OptionList",
    "OptionName",
    "OptionNumber",
    "OptionString",
    "OptionValue",
    "PlateDrawStep",
    "ProgramDecl",
    "ProgramParam",
    "ProgramStep",
    "ReturnStep",
    "RuleDecl",
    "SampleStep",
    "ScalarParam",
    "SchemaDecl",
    "SchemaParameter",
    "SequentRule",
    "SignatureDecl",
    "SortDecl",
    "SortDim",
    "SortVocabLiteral",
    "Statement",
    "TypeCoproduct",
    "TypeDecl",
    "TypeEffectApply",
    "TypeEnumSet",
    "TypeExpr",
    "TypeFreeMonoid",
    "TypeFreeResiduated",
    "TypeFromExpr",
    "TypeInitializer",
    "TypeName",
    "TypeProduct",
    "TypeSlash",
    "VectorisedObserveStep",
    "VertexKindDecl",
]
