"""Category types for categorial grammars.

Provides the free algebra of grammatical categories generated by
atoms and type constructors. This is the type system underlying
chart parsers for CCG, the Lambek calculus, multimodal type-logical
grammar, and any bespoke formalism assembled from biclosed monoidal
primitives.

Atomic categories
-----------------
``AtomicCategory(name="S")`` — a basic category like S, NP, N, PP.

Slash categories (internal homs)
--------------------------------
``SlashCategory(result=R, argument=A, direction="/")``  — right residual: R/A
``SlashCategory(result=R, argument=A, direction="\\")`` — left residual: R\\A

Product categories (tensor product)
------------------------------------
``ProductCategory(left=L, right=R)`` — tensor: L ⊗ R

Unit category (monoidal unit)
-----------------------------
``UnitCategory()`` — the monoidal unit I satisfying I ⊗ A ≅ A ≅ A ⊗ I.

Modal categories (unary type constructors)
------------------------------------------
``ModalCategory(modality="◇", inner=A)`` — a modality applied to a category.

Category systems
----------------
A ``CategorySystem`` manages a finite inventory of categories
with integer indices, supporting lookup and enumeration.
"""

from collections.abc import Callable, Iterator
from typing import Literal

import didactic.api as dx


# ---------------------------------------------------------------------------
# the five-variant Category sum
# ---------------------------------------------------------------------------


class Category(dx.TaggedUnion, discriminator="kind"):
    """Sum of grammatical category kinds.

    Variants subclass this root and pin ``kind`` to a literal value;
    ``Category.model_validate`` dispatches on that discriminator.
    """


class AtomicCategory(Category):
    """An atomic (primitive) grammatical category."""

    name: str
    kind: Literal["atomic"] = "atomic"

    def __str__(self) -> str:
        return self.name


class SlashCategory(Category):
    """A complex category formed by a slash operator.

    ``result/argument`` (forward): seeks argument on the right.
    ``result\\argument`` (backward): seeks argument on the left.

    These are the internal homs of a biclosed monoidal category:
    ``/`` is the right residual and ``\\`` is the left residual.
    """

    result: Category
    argument: Category
    direction: Literal["/", "\\"]
    kind: Literal["slash"] = "slash"

    def __str__(self) -> str:
        res = _cat_str(self.result)
        arg = _cat_str(self.argument)
        if isinstance(self.result, SlashCategory):
            res = f"({res})"
        if isinstance(self.argument, SlashCategory):
            arg = f"({arg})"
        return f"{res}{self.direction}{arg}"


class ProductCategory(Category):
    """A product category (tensor product) for type-logical grammar.

    Represents A ⊗ B in the Lambek calculus.
    """

    left: Category
    right: Category
    kind: Literal["product"] = "product"

    def __str__(self) -> str:
        l = _cat_str(self.left)
        r = _cat_str(self.right)
        if isinstance(self.left, (SlashCategory, ProductCategory)):
            l = f"({l})"
        if isinstance(self.right, (SlashCategory, ProductCategory)):
            r = f"({r})"
        return f"{l}⊗{r}"


class UnitCategory(Category):
    """The monoidal unit category I.

    Satisfies the unit laws: I ⊗ A ≅ A ≅ A ⊗ I.
    """

    kind: Literal["unit"] = "unit"

    def __str__(self) -> str:
        return "I"


class ModalCategory(Category):
    """A modal category: a unary type constructor applied to a category.

    Represents modalities like ◇A (diamond) and □A (box) used in
    multimodal type-logical grammar (Moortgat 1997). Arbitrary
    named modalities are supported.
    """

    modality: str
    inner: Category
    kind: Literal["modal"] = "modal"

    def __str__(self) -> str:
        inner_str = _cat_str(self.inner)
        if isinstance(self.inner, (SlashCategory, ProductCategory)):
            inner_str = f"({inner_str})"
        return f"{self.modality}{inner_str}"


# all concrete category types for isinstance checks
_CATEGORY_TYPES = (
    AtomicCategory,
    SlashCategory,
    ProductCategory,
    UnitCategory,
    ModalCategory,
)


def _cat_str(cat: Category) -> str:
    """Domain-formatted string for a category (uses each variant's __str__)."""
    return str(cat)


# ================================================================
# built-in constructor names for from_generators
# ================================================================


def _slash_constructor(current: list[Category]) -> list[Category]:
    """Generate all slash categories from current inventory."""
    new: list[Category] = []
    for result in current:
        for arg in current:
            new.append(SlashCategory(result=result, argument=arg, direction="/"))
            new.append(SlashCategory(result=result, argument=arg, direction="\\"))
    return new


def _product_constructor(current: list[Category]) -> list[Category]:
    """Generate all product categories from current inventory."""
    new: list[Category] = []
    for left in current:
        for right in current:
            new.append(ProductCategory(left=left, right=right))
    return new


def _unit_constructor(current: list[Category]) -> list[Category]:
    """Generate the unit category (only once)."""
    return [UnitCategory()]


def _modal_constructor(
    modality: str,
) -> Callable[[list[Category]], list[Category]]:
    """Create a modal constructor for a specific modality."""

    def constructor(current: list[Category]) -> list[Category]:
        return [ModalCategory(modality=modality, inner=c) for c in current]

    return constructor


# registry of built-in constructors
_BUILTIN_CONSTRUCTORS: dict[str, Callable[[list[Category]], list[Category]]] = {
    "slash": _slash_constructor,
    "product": _product_constructor,
    "unit": _unit_constructor,
    "diamond": _modal_constructor("◇"),
    "box": _modal_constructor("□"),
}


# ---------------------------------------------------------------------------
# CategorySystem
# ---------------------------------------------------------------------------


class CategorySystem:
    """A finite inventory of grammatical categories with integer indices.

    Manages the mapping between ``Category`` objects and their integer
    indices, used by chart parsers.

    Parameters
    ----------
    categories : list of Category
        The initial category inventory.
    """

    def __init__(self, categories: list[Category] | None = None) -> None:
        self._cats: list[Category] = []
        self._index: dict[Category, int] = {}
        if categories:
            for cat in categories:
                self.add(cat)

    @classmethod
    def from_atoms(cls, names: list[str]) -> "CategorySystem":
        """Create a category system from atomic category names."""
        cats: list[Category] = [AtomicCategory(name=name) for name in names]
        return cls(cats)

    @classmethod
    def from_atoms_and_slash_depth(
        cls,
        names: list[str],
        max_depth: int = 1,
    ) -> "CategorySystem":
        """Create a category system with atomic categories and all
        slash combinations up to a given depth.
        """
        system = cls.from_atoms(names)
        if max_depth < 1:
            return system
        for _ in range(max_depth):
            current = list(system._cats)
            for result in current:
                for arg in current:
                    system.add(
                        SlashCategory(result=result, argument=arg, direction="/")
                    )
                    system.add(
                        SlashCategory(result=result, argument=arg, direction="\\")
                    )
        return system

    @classmethod
    def from_generators(
        cls,
        atoms: list[str],
        constructors: list[str] | None = None,
        max_depth: int = 1,
    ) -> "CategorySystem":
        """Create a category system from atoms and type constructors.

        Built-in constructor names:

        - ``"slash"`` — generates all A/B and A\\B
        - ``"product"`` — generates all A⊗B
        - ``"unit"`` — adds the monoidal unit I
        - ``"diamond"`` — generates ◇A for all A
        - ``"box"`` — generates □A for all A
        """
        if constructors is None:
            constructors = ["slash"]

        fns = []
        for name in constructors:
            if name not in _BUILTIN_CONSTRUCTORS:
                raise ValueError(
                    f"unknown constructor {name!r}; available: "
                    f"{sorted(_BUILTIN_CONSTRUCTORS.keys())}"
                )
            fns.append(_BUILTIN_CONSTRUCTORS[name])

        system = cls.from_atoms(atoms)
        for _ in range(max_depth):
            current = list(system._cats)
            for fn in fns:
                for cat in fn(current):
                    system.add(cat)
        return system

    def add(self, cat: Category) -> int:
        """Add a category to the system; return its index."""
        if cat in self._index:
            return self._index[cat]
        idx = len(self._cats)
        self._cats.append(cat)
        self._index[cat] = idx
        return idx

    def add_slash(
        self,
        result: Category,
        argument: Category,
        direction: Literal["/", "\\"],
    ) -> int:
        """Add a slash category and return its index."""
        cat = SlashCategory(result=result, argument=argument, direction=direction)
        return self.add(cat)

    @property
    def size(self) -> int:
        """Number of categories in the system."""
        return len(self._cats)

    def __len__(self) -> int:
        return len(self._cats)

    def __getitem__(self, key: str | int | Category) -> Category | int:
        """Look up by name (str), index (int), or category object."""
        if isinstance(key, str):
            cat = AtomicCategory(name=key)
            if cat not in self._index:
                raise KeyError(f"category {key!r} not in system")
            return cat

        if isinstance(key, int):
            if key < 0 or key >= len(self._cats):
                raise KeyError(f"index {key} out of range")
            return self._cats[key]

        if isinstance(key, _CATEGORY_TYPES):
            if key not in self._index:
                raise KeyError(f"category {key!r} not in system")
            return self._index[key]

        raise TypeError(f"invalid key type: {type(key).__name__}")

    def index(self, cat: Category) -> int:
        """Get the integer index of a category."""
        if cat not in self._index:
            raise KeyError(f"category {cat!r} not in system")
        return self._index[cat]

    def __contains__(self, cat: Category) -> bool:
        return cat in self._index

    def __iter__(self) -> Iterator[Category]:
        return iter(self._cats)

    def __repr__(self) -> str:
        cats_str = ", ".join(str(c) for c in self._cats[:10])
        if len(self._cats) > 10:
            cats_str += f", ... ({len(self._cats)} total)"
        return f"CategorySystem([{cats_str}])"
