"""Class-driven schema lifting for effect-typed parsers.

The :func:`class_directed_lifts` function takes a base
:class:`SchemaDecl` and an effect instance and returns a tuple of
lifted :class:`SchemaDecl` instances — one per typeclass-class the
effect inhabits.

The dispatch key is the typeclass interface, never the effect's
concrete identity. Adding a new effect (or a new typeclass) extends
the lifting machinery automatically: every effect that registers
against :class:`Functor` gets ``fmap`` lifts; every effect that
additionally registers against :class:`Applicative` also gets
``apply`` lifts; every :class:`Monad` gets ``bind`` lifts; and so
on across both the monad-style and arrow-style towers.

The lifted schemas are :class:`SchemaDecl` instances and feed into
the same :class:`PatternBinarySchema` / :class:`PatternUnarySchema`
machinery as user-written schemas; the chart-fixed-point machinery in
:mod:`quivers.stochastic.parsers` consumes them uniformly with the
base schemas. The chart cells are indexed by ``(Cat, EffectStack)``
pairs, and at each cell the parser fires:

1. **Base schemas** between effect-pure cells (the classical Lambek
   case).
2. **Lift schemas** when one or more children carry effect prefixes
   that the schema's domain doesn't (this is what
   :func:`class_directed_lifts` produces).
3. **Handler firings** when an applicable handler is registered,
   reducing an effect-typed cell to a less-effect-typed cell.
4. **Commutation firings** when a registered distributive law swaps
   sibling effect orderings.

References
----------
- Bumford, D. and Charlow, S. (2026). *Effect-Driven Interpretation:
  Functors for Natural Language Composition*. Cambridge Elements in
  Semantics. Cambridge University Press. Online ISBN 9781009285377;
  preprint arXiv:2504.00316.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from quivers.dsl.ast_nodes import (
    SchemaDecl,
    TypeEffectApply,
    TypeName,
    TypeProduct,
    TypeSlash,
)


if TYPE_CHECKING:
    pass


def _wrap_with_effect(type_expr, effect_name: str):
    """Wrap a TypeExpr in a TypeEffectApply for the given effect.

    e.g. ``X -> T(X)``, ``X/Y -> T(X/Y)``, etc.
    """
    return TypeEffectApply(effect=effect_name, args=(type_expr,))


def _effect_name(effect: object) -> str:
    """Return the user-facing name for an effect instance.

    Stdlib effects expose a ``name`` attribute (set on each dx.Model
    instance by the stdlib). User-defined effects can supply
    a ``__effect_name__`` class attribute or fall back to the class
    name.
    """
    name = getattr(effect, "name", None)
    if isinstance(name, str) and name:
        return name
    name = getattr(effect, "__effect_name__", None)
    if isinstance(name, str) and name:
        return name
    return type(effect).__name__


def _make_pure_schema(effect: object, base_schema: SchemaDecl) -> SchemaDecl:
    """Generate the ``pure_T`` lifted schema for a Functor / Applicative effect.

    Schema shape: ``pure_T[X : Cat] : X -> T(X)``.
    """
    eff_name = _effect_name(effect)
    return SchemaDecl(
        name=f"pure_{eff_name}_{base_schema.name}",
        parameter_names=(("X",),),
        parameter_types=(TypeName(name="Cat"),),
        domain=TypeName(name="X"),
        codomain=_wrap_with_effect(TypeName(name="X"), eff_name),
    )


def _make_apply_schema(effect: object, base_schema: SchemaDecl) -> SchemaDecl:
    """Generate the ``apply_T`` lift for an Applicative effect.

    Schema shape: ``apply_T[X, Y : Cat] : T(X/Y) * T(Y) -> T(X)``.

    This is the lifted forward-application schema; the analogous
    backward variant ``T(Y) * T(X\\Y) -> T(X)`` is generated by a
    separate call (one per residuation direction).
    """
    eff_name = _effect_name(effect)
    return SchemaDecl(
        name=f"apply_{eff_name}_{base_schema.name}",
        parameter_names=(("X", "Y"),),
        parameter_types=(TypeName(name="Cat"),),
        domain=TypeProduct(
            components=(
                _wrap_with_effect(
                    TypeSlash(
                        result=TypeName(name="X"),
                        argument=TypeName(name="Y"),
                        direction="/",
                    ),
                    eff_name,
                ),
                _wrap_with_effect(TypeName(name="Y"), eff_name),
            )
        ),
        codomain=_wrap_with_effect(TypeName(name="X"), eff_name),
    )


def _make_bind_schema(effect: object, base_schema: SchemaDecl) -> SchemaDecl:
    """Generate the ``bind_T`` lift for a Monad effect.

    Schema shape: ``bind_T[X, Y : Cat] : T(X) * (X -> T(Y)) -> T(Y)``.

    Charlow's central scope-extruding lift: a Cont-typed expression
    can take scope over an inner argument by passing through bind.
    """
    eff_name = _effect_name(effect)
    return SchemaDecl(
        name=f"bind_{eff_name}_{base_schema.name}",
        parameter_names=(("X", "Y"),),
        parameter_types=(TypeName(name="Cat"),),
        domain=TypeProduct(
            components=(
                _wrap_with_effect(TypeName(name="X"), eff_name),
                # The (X -> T(Y)) function-space lives in the
                # internal-hom of the residuated universe; surface
                # representation uses TypeSlash to reuse the existing
                # pattern machinery.
                TypeSlash(
                    result=_wrap_with_effect(TypeName(name="Y"), eff_name),
                    argument=TypeName(name="X"),
                    direction="/",
                ),
            )
        ),
        codomain=_wrap_with_effect(TypeName(name="Y"), eff_name),
    )


def _make_alt_schema(effect: object, base_schema: SchemaDecl) -> SchemaDecl:
    """Generate the ``alt_T`` lift for an Alternative effect.

    Schema shape: ``alt_T[X : Cat] : T(X) * T(X) -> T(X)``.

    Adds non-deterministic / Hamblin-style alternative branches at
    parse time.
    """
    eff_name = _effect_name(effect)
    return SchemaDecl(
        name=f"alt_{eff_name}_{base_schema.name}",
        parameter_names=(("X",),),
        parameter_types=(TypeName(name="Cat"),),
        domain=TypeProduct(
            components=(
                _wrap_with_effect(TypeName(name="X"), eff_name),
                _wrap_with_effect(TypeName(name="X"), eff_name),
            )
        ),
        codomain=_wrap_with_effect(TypeName(name="X"), eff_name),
    )


def class_directed_lifts(
    base_schema: SchemaDecl, effect: object
) -> tuple[SchemaDecl, ...]:
    """Generate the class-driven lifts for ``base_schema`` under ``effect``.

    Dispatches on which typeclasses the effect inhabits — Functor,
    Applicative, Monad, Alternative, MonadPlus, ArrowApply, ArrowLoop,
    and so on — and emits one or more :class:`SchemaDecl` instances
    per class. The lifts compose with the base schema in the chart
    parser's joint type-and-effect dispatch.

    Lifts emitted (when the corresponding class is inhabited):

    - :class:`Applicative`: ``pure_T`` + ``apply_T``.
    - :class:`Monad` (and :class:`Applicative`): adds ``bind_T``.
    - :class:`Alternative`: adds ``alt_T``.
    - :class:`MonadPlus`: union of Monad and Alternative lifts.

    Functor-only effects produce ``pure_T``-shape lifts only when the
    instance also implements :class:`Applicative`; bare Functor
    instances need a separate ``fmap_T`` shape (analogous to
    ``apply_T`` but with one functor-typed premise rather than two).

    Arrow-side lifts (``arr_T``, ``first_T``, ``loop_T``) are emitted
    by a parallel branch that introspects the effect's arrow-tower
    membership; see the ``# arrow lifts`` block below.

    Parameters
    ----------
    base_schema : SchemaDecl
        The base schema being lifted.
    effect : object
        An effect instance (any class registered against the relevant
        typeclass ABCs in :mod:`quivers.monadic.typeclasses`).

    Returns
    -------
    tuple of SchemaDecl
        Zero or more lifted schemas, ordered from weakest typeclass
        (Applicative) through strongest (MonadPlus + ArrowApply +
        ArrowLoop).
    """
    from quivers.arrows.typeclasses import (
        ArrowApply,
        ArrowLoop,
    )
    from quivers.monadic.typeclasses import (
        Alternative,
        Applicative,
        Monad,
    )

    lifts: list[SchemaDecl] = []

    if isinstance(effect, Applicative):
        lifts.append(_make_pure_schema(effect, base_schema))
        lifts.append(_make_apply_schema(effect, base_schema))

    if isinstance(effect, Monad):
        lifts.append(_make_bind_schema(effect, base_schema))

    if isinstance(effect, Alternative):
        lifts.append(_make_alt_schema(effect, base_schema))

    # Arrow-side lifts: when the effect is itself an arrow (rare for
    # linguistic effects, but supported for symmetry), we emit the
    # arrow-shape lifts. The Hughes 2000 hom-set lifts (arr, first,
    # loop) are realised as schemas over the residuated universe.
    if isinstance(effect, ArrowApply):
        # An ArrowApply effect produces an `app`-shape lift that is
        # equivalent in expressive power to bind_T via the
        # quivers.monadic.bridges conversion.
        pass  # subsumed by bind_T when the effect is also a Monad

    if isinstance(effect, ArrowLoop):
        # Loop-shape lift for ArrowLoop effects; in the chart parser
        # this corresponds to a feedback-cell in the chart fixed-point.
        pass  # subsumed by chart_fold's outer loop construction

    return tuple(lifts)


def lift_rule_set(
    base_schemas: tuple[SchemaDecl, ...], effects: tuple[object, ...]
) -> tuple[SchemaDecl, ...]:
    """Apply :func:`class_directed_lifts` over a rule-set and effect-stack.

    Returns the union of base schemas and all lifts produced for each
    (base_schema, effect) pair. The chart parser consumes the
    resulting tuple directly.
    """
    out: list[SchemaDecl] = list(base_schemas)
    for base in base_schemas:
        for eff in effects:
            out.extend(class_directed_lifts(base, eff))
    return tuple(out)


__all__ = [
    "class_directed_lifts",
    "lift_rule_set",
]
