"""The published support page must equal a fresh measurement.

`docs/transpile-support.md` is generated by
[`support_matrix`][tests.transpile.support_matrix]: it transpiles every
gallery program and every construct fixture against every backend and
writes the outcomes. This module repeats that measurement and requires
the committed page to match it byte for byte, so a support change also
requires regenerating the page.
"""

from __future__ import annotations

from tests.transpile import support_matrix


def test_published_support_page_matches_a_fresh_measurement() -> None:
    """Regenerating the page reproduces what is committed."""
    committed = support_matrix.DOC_PATH.read_text(encoding="utf-8")
    measured = support_matrix.render_page(support_matrix.measure())
    assert measured == committed, (
        f"{support_matrix.DOC_PATH.name} disagrees with a fresh "
        f"measurement, so the page no longer describes the "
        f"transpiler. Regenerate it with `python -m "
        f"tests.transpile.support_matrix` and commit the result. If "
        f"the diff is a support change you intended, the regenerated "
        f"page is the record of it."
    )
