"""Transpile a compiled QVR module to other probabilistic-programming
languages.

The pipeline is a `didactic.api.Mapping`
composition of three arrows:

    Module --Lower--> IRProgram --Renderer[T]--> panproto.Schema --emit_pretty--> bytes

[`Lower`][quivers.transpile.plan.Lower] is target-independent; it
elaborates the parsed module to its checked kernel module and derives
the program's plan from its computation: an
[`IRProgram`][quivers.transpile.ir.IRProgram] carrying the module and
the plan's nodes (sample, observe, marginalize, ...), each with the
support / plate / argument shape read off the module's types,
[`FAMILY_META`][quivers.transpile.family_meta.FAMILY_META], and
[`torch.distributions.Distribution.arg_constraints`][torch.distributions.distribution.Distribution.arg_constraints].

Each target `T` has its own
[`Renderer[T]`][quivers.transpile.renderers.RendererBase]
subclass in `quivers.transpile.renderers.<target>`; the renderer
consumes the IR and emits a target-specific
`panproto.Schema`. The renderer's idiom (Stan's
`block` structure, NumPyro's `plate` contexts, BUGS's row-loop
relations) is the only place target-specific vocabulary lives.

Family-level facts (per-target distribution name, argument aliases)
live in `FAMILY_META`; no renderer hardcodes family-name dispatch.
"""

from __future__ import annotations

import importlib
import types
from typing import TYPE_CHECKING, TypeAliasType

# The DSL compiler reads this package's family metadata while it
# initializes, and the metadata's IR reads the DSL's AST. Initializing the
# DSL before any leaf module gives every entry into either package the
# same order: the DSL starts, its compiler loads the family metadata, and
# that load finds the DSL's AST modules already importable.
import quivers.dsl  # noqa: F401
from quivers.transpile._api import (
    CATEGORICAL_METADATA_IGNORABLE,
    CHURCH_LIKE,
    PYTHON_DEEP,
    QIEC_SURFACE,
    STAN_LIKE,
    UnsupportedConstruct,
)
from quivers.transpile._diagnostics import RefusedDeclaration

if TYPE_CHECKING:
    from quivers.transpile._entry import (
        available_targets,
        transpile,
    )
    from quivers.transpile._pipeline import (
        EmitPretty,
        parser_registry,
        target_protocol,
    )
    from quivers.transpile._support import (
        Backend,
        unsupported_for,
    )
    from quivers.transpile.family_meta import (
        ClassIndexOutcome,
        FAMILY_META,
        FamilyMeta,
        MarginalizeAtomSet,
        MarginalizeSupport,
        class_index_outcome,
        finite_enumerable_at_call_site,
        marginalize_support,
    )
    from quivers.transpile.family_spelling import (
        DYNAMIC_TARGET_LANGUAGES,
        DistributionSpelling,
        bridge_source,
        can_spell,
        helper_families,
        helper_roots,
        spell_distribution,
    )
    from quivers.transpile.ir import (
        CSBoolean,
        CSCorrCholesky,
        CSIntegerInterval,
        CSInterval,
        CSLowerCholesky,
        CSNonnegativeInteger,
        CSOneHot,
        CSPositive,
        CSPositiveDefinite,
        CSPositiveInteger,
        CSReal,
        CSRealMatrix,
        CSRealVector,
        CSSimplex,
        CSUnitInterval,
        ConstraintSpec,
        Dim,
        DimDynamic,
        DimStatic,
        DomainGridAxis,
        EventAxisSource,
        IRArg,
        IRArgBroadcast,
        IRArgFamilyRef,
        IRArgKernel,
        IRArgList,
        IRArgMatrix,
        IRArgNumber,
        IRArgRef,
        IRCall,
        IRDataInput,
        IRDeterministic,
        IRMarginalize,
        IRNode,
        IRObserve,
        IRProgram,
        IRQiecValueExpr,
        IRReturn,
        IRSample,
        IRScore,
        LetAffineSource,
        LetExprAffineMap,
        OverOrCodomainAxes,
        Plate,
        StructuredArgSpec,
        StructuredDataArg,
        StructuredKernelArg,
        StructuredSampleLowering,
        StructuredZeroVectorArg,
        affine_column_offsets,
        affine_domain_width,
        event_dim_of,
        event_shape_of,
        from_constraint,
        is_int_bit,
        is_int_category,
        is_int_count,
        is_real_bounded_interval,
        is_real_corr_chol,
        is_real_cov_matrix,
        is_real_matrix,
        is_real_one_hot,
        is_real_positive,
        is_real_scalar,
        is_real_simplex,
        is_real_unit_interval,
        is_real_vector,
        real_interval_bounds,
    )
    from quivers.transpile.plan import (
        Lower,
        TARGET_NAME_SEPARATOR,
        checked_module,
        checked_program_plan,
        program_plan,
        target_name,
    )
    from quivers.transpile.qiec_ir import (
        IRQiecAffineMap,
        IRQiecArgumentDef,
        IRQiecArrowKind,
        IRQiecAttachmentRef,
        IRQiecBind,
        IRQiecBindStep,
        IRQiecBinder,
        IRQiecBoolLiteral,
        IRQiecBranchGiven,
        IRQiecBytesLiteral,
        IRQiecCall,
        IRQiecCase,
        IRQiecCaseBranch,
        IRQiecCaseMotive,
        IRQiecComprehension,
        IRQiecComputation,
        IRQiecComputationType,
        IRQiecConstructorDecl,
        IRQiecConstructorValue,
        IRQiecContextSort,
        IRQiecDistributionValue,
        IRQiecDynamicAddressFrame,
        IRQiecEffectBinder,
        IRQiecEffectDef,
        IRQiecEffectKind,
        IRQiecEffectRef,
        IRQiecEffectRequest,
        IRQiecEffectRow,
        IRQiecEffectVariable,
        IRQiecEqualityType,
        IRQiecEvidence,
        IRQiecEvidenceValue,
        IRQiecFamilyDecl,
        IRQiecFieldDef,
        IRQiecFloatLiteral,
        IRQiecFunctionType,
        IRQiecGather,
        IRQiecHandle,
        IRQiecHandlerClauseDef,
        IRQiecHandlerDef,
        IRQiecHandlerReturnClauseDef,
        IRQiecId,
        IRQiecIf,
        IRQiecIndexBinder,
        IRQiecIndexConstructor,
        IRQiecIndexLiteral,
        IRQiecIndexSort,
        IRQiecIndexVariable,
        IRQiecIntLiteral,
        IRQiecKernelMatrix,
        IRQiecKind,
        IRQiecLiteral,
        IRQiecLiteralValue,
        IRQiecLocal,
        IRQiecLogDensity,
        IRQiecModule,
        IRQiecNamedArgument,
        IRQiecNamedComputation,
        IRQiecNamedEffectInstance,
        IRQiecNatSort,
        IRQiecNewInstance,
        IRQiecNullLiteral,
        IRQiecOperationDef,
        IRQiecPerform,
        IRQiecPlateAxis,
        IRQiecPlateShape,
        IRQiecPrimitiveApplication,
        IRQiecProgramEntry,
        IRQiecProgramParameter,
        IRQiecProgramSite,
        IRQiecProjection,
        IRQiecReduction,
        IRQiecReflexivity,
        IRQiecResume,
        IRQiecReturn,
        IRQiecRowEntry,
        IRQiecRowKind,
        IRQiecRowVariable,
        IRQiecRowwise,
        IRQiecSegmentSum,
        IRQiecShapeIndex,
        IRQiecShapeSort,
        IRQiecSiteProvenance,
        IRQiecSiteValue,
        IRQiecSourceOrigin,
        IRQiecStatic,
        IRQiecStringLiteral,
        IRQiecTableMap,
        IRQiecTensorValue,
        IRQiecTransportValue,
        IRQiecTupleLiteral,
        IRQiecTupleValue,
        IRQiecTypeApplication,
        IRQiecTypeBinder,
        IRQiecTypeConstructor,
        IRQiecTypeKind,
        IRQiecTypeVariable,
        IRQiecUserIndexSort,
        IRQiecValue,
        IRQiecVar,
        IRQiecWeightSum,
        QiecCapabilityDiagnostic,
        QiecFeature,
        QiecTargetCapabilities,
        analyze_qiec_capabilities,
        capabilities_for_target,
        host_runtime_capability_diagnostics,
        lower_qiec_ir,
    )
    from quivers.transpile.renderer_registry import (
        BackendRenderer,
        EmitFn,
        RendererDuplicateError,
        RendererLookupError,
        emit_hook,
        get_emit,
        registered_backends,
        registered_node_types,
        unregister,
    )


# Every other public name binds on first access. The leaf modules reach
# the DSL compiler, and the DSL compiler imports this package (for the
# family metadata) while it initializes, so importing them here would
# close a cycle.
_LAZY_EXPORTS: dict[str, str] = {
    "Backend": "quivers.transpile._support",
    "BackendRenderer": "quivers.transpile.renderer_registry",
    "CSBoolean": "quivers.transpile.ir",
    "CSCorrCholesky": "quivers.transpile.ir",
    "CSIntegerInterval": "quivers.transpile.ir",
    "CSInterval": "quivers.transpile.ir",
    "CSLowerCholesky": "quivers.transpile.ir",
    "CSNonnegativeInteger": "quivers.transpile.ir",
    "CSOneHot": "quivers.transpile.ir",
    "CSPositive": "quivers.transpile.ir",
    "CSPositiveDefinite": "quivers.transpile.ir",
    "CSPositiveInteger": "quivers.transpile.ir",
    "CSReal": "quivers.transpile.ir",
    "CSRealMatrix": "quivers.transpile.ir",
    "CSRealVector": "quivers.transpile.ir",
    "CSSimplex": "quivers.transpile.ir",
    "CSUnitInterval": "quivers.transpile.ir",
    "ClassIndexOutcome": "quivers.transpile.family_meta",
    "ConstraintSpec": "quivers.transpile.ir",
    "DYNAMIC_TARGET_LANGUAGES": "quivers.transpile.family_spelling",
    "Dim": "quivers.transpile.ir",
    "DimDynamic": "quivers.transpile.ir",
    "DimStatic": "quivers.transpile.ir",
    "DistributionSpelling": "quivers.transpile.family_spelling",
    "DomainGridAxis": "quivers.transpile.ir",
    "EmitFn": "quivers.transpile.renderer_registry",
    "EmitPretty": "quivers.transpile._pipeline",
    "EventAxisSource": "quivers.transpile.ir",
    "FAMILY_META": "quivers.transpile.family_meta",
    "FamilyMeta": "quivers.transpile.family_meta",
    "IRArg": "quivers.transpile.ir",
    "IRArgBroadcast": "quivers.transpile.ir",
    "IRArgFamilyRef": "quivers.transpile.ir",
    "IRArgKernel": "quivers.transpile.ir",
    "IRArgList": "quivers.transpile.ir",
    "IRArgMatrix": "quivers.transpile.ir",
    "IRArgNumber": "quivers.transpile.ir",
    "IRArgRef": "quivers.transpile.ir",
    "IRCall": "quivers.transpile.ir",
    "IRDataInput": "quivers.transpile.ir",
    "IRDeterministic": "quivers.transpile.ir",
    "IRMarginalize": "quivers.transpile.ir",
    "IRNode": "quivers.transpile.ir",
    "IRObserve": "quivers.transpile.ir",
    "IRProgram": "quivers.transpile.ir",
    "IRQiecAffineMap": "quivers.transpile.qiec_ir",
    "IRQiecArgumentDef": "quivers.transpile.qiec_ir",
    "IRQiecArrowKind": "quivers.transpile.qiec_ir",
    "IRQiecAttachmentRef": "quivers.transpile.qiec_ir",
    "IRQiecBind": "quivers.transpile.qiec_ir",
    "IRQiecBindStep": "quivers.transpile.qiec_ir",
    "IRQiecBinder": "quivers.transpile.qiec_ir",
    "IRQiecBoolLiteral": "quivers.transpile.qiec_ir",
    "IRQiecBranchGiven": "quivers.transpile.qiec_ir",
    "IRQiecBytesLiteral": "quivers.transpile.qiec_ir",
    "IRQiecCall": "quivers.transpile.qiec_ir",
    "IRQiecCase": "quivers.transpile.qiec_ir",
    "IRQiecCaseBranch": "quivers.transpile.qiec_ir",
    "IRQiecCaseMotive": "quivers.transpile.qiec_ir",
    "IRQiecComprehension": "quivers.transpile.qiec_ir",
    "IRQiecComputation": "quivers.transpile.qiec_ir",
    "IRQiecComputationType": "quivers.transpile.qiec_ir",
    "IRQiecConstructorDecl": "quivers.transpile.qiec_ir",
    "IRQiecConstructorValue": "quivers.transpile.qiec_ir",
    "IRQiecContextSort": "quivers.transpile.qiec_ir",
    "IRQiecDistributionValue": "quivers.transpile.qiec_ir",
    "IRQiecDynamicAddressFrame": "quivers.transpile.qiec_ir",
    "IRQiecEffectBinder": "quivers.transpile.qiec_ir",
    "IRQiecEffectDef": "quivers.transpile.qiec_ir",
    "IRQiecEffectKind": "quivers.transpile.qiec_ir",
    "IRQiecEffectRef": "quivers.transpile.qiec_ir",
    "IRQiecEffectRequest": "quivers.transpile.qiec_ir",
    "IRQiecEffectRow": "quivers.transpile.qiec_ir",
    "IRQiecEffectVariable": "quivers.transpile.qiec_ir",
    "IRQiecEqualityType": "quivers.transpile.qiec_ir",
    "IRQiecEvidence": "quivers.transpile.qiec_ir",
    "IRQiecEvidenceValue": "quivers.transpile.qiec_ir",
    "IRQiecFamilyDecl": "quivers.transpile.qiec_ir",
    "IRQiecFieldDef": "quivers.transpile.qiec_ir",
    "IRQiecFloatLiteral": "quivers.transpile.qiec_ir",
    "IRQiecFunctionType": "quivers.transpile.qiec_ir",
    "IRQiecGather": "quivers.transpile.qiec_ir",
    "IRQiecHandle": "quivers.transpile.qiec_ir",
    "IRQiecHandlerClauseDef": "quivers.transpile.qiec_ir",
    "IRQiecHandlerDef": "quivers.transpile.qiec_ir",
    "IRQiecHandlerReturnClauseDef": "quivers.transpile.qiec_ir",
    "IRQiecId": "quivers.transpile.qiec_ir",
    "IRQiecIf": "quivers.transpile.qiec_ir",
    "IRQiecIndexBinder": "quivers.transpile.qiec_ir",
    "IRQiecIndexConstructor": "quivers.transpile.qiec_ir",
    "IRQiecIndexLiteral": "quivers.transpile.qiec_ir",
    "IRQiecIndexSort": "quivers.transpile.qiec_ir",
    "IRQiecIndexVariable": "quivers.transpile.qiec_ir",
    "IRQiecIntLiteral": "quivers.transpile.qiec_ir",
    "IRQiecKernelMatrix": "quivers.transpile.qiec_ir",
    "IRQiecKind": "quivers.transpile.qiec_ir",
    "IRQiecLiteral": "quivers.transpile.qiec_ir",
    "IRQiecLiteralValue": "quivers.transpile.qiec_ir",
    "IRQiecLocal": "quivers.transpile.qiec_ir",
    "IRQiecLogDensity": "quivers.transpile.qiec_ir",
    "IRQiecModule": "quivers.transpile.qiec_ir",
    "IRQiecNamedArgument": "quivers.transpile.qiec_ir",
    "IRQiecNamedComputation": "quivers.transpile.qiec_ir",
    "IRQiecNamedEffectInstance": "quivers.transpile.qiec_ir",
    "IRQiecNatSort": "quivers.transpile.qiec_ir",
    "IRQiecNewInstance": "quivers.transpile.qiec_ir",
    "IRQiecNullLiteral": "quivers.transpile.qiec_ir",
    "IRQiecOperationDef": "quivers.transpile.qiec_ir",
    "IRQiecPerform": "quivers.transpile.qiec_ir",
    "IRQiecPlateAxis": "quivers.transpile.qiec_ir",
    "IRQiecPlateShape": "quivers.transpile.qiec_ir",
    "IRQiecPrimitiveApplication": "quivers.transpile.qiec_ir",
    "IRQiecProgramEntry": "quivers.transpile.qiec_ir",
    "IRQiecProgramParameter": "quivers.transpile.qiec_ir",
    "IRQiecProgramSite": "quivers.transpile.qiec_ir",
    "IRQiecProjection": "quivers.transpile.qiec_ir",
    "IRQiecReduction": "quivers.transpile.qiec_ir",
    "IRQiecReflexivity": "quivers.transpile.qiec_ir",
    "IRQiecResume": "quivers.transpile.qiec_ir",
    "IRQiecReturn": "quivers.transpile.qiec_ir",
    "IRQiecRowEntry": "quivers.transpile.qiec_ir",
    "IRQiecRowKind": "quivers.transpile.qiec_ir",
    "IRQiecRowVariable": "quivers.transpile.qiec_ir",
    "IRQiecRowwise": "quivers.transpile.qiec_ir",
    "IRQiecSegmentSum": "quivers.transpile.qiec_ir",
    "IRQiecShapeIndex": "quivers.transpile.qiec_ir",
    "IRQiecShapeSort": "quivers.transpile.qiec_ir",
    "IRQiecSiteProvenance": "quivers.transpile.qiec_ir",
    "IRQiecSiteValue": "quivers.transpile.qiec_ir",
    "IRQiecSourceOrigin": "quivers.transpile.qiec_ir",
    "IRQiecStatic": "quivers.transpile.qiec_ir",
    "IRQiecStringLiteral": "quivers.transpile.qiec_ir",
    "IRQiecTableMap": "quivers.transpile.qiec_ir",
    "IRQiecTensorValue": "quivers.transpile.qiec_ir",
    "IRQiecTransportValue": "quivers.transpile.qiec_ir",
    "IRQiecTupleLiteral": "quivers.transpile.qiec_ir",
    "IRQiecTupleValue": "quivers.transpile.qiec_ir",
    "IRQiecTypeApplication": "quivers.transpile.qiec_ir",
    "IRQiecTypeBinder": "quivers.transpile.qiec_ir",
    "IRQiecTypeConstructor": "quivers.transpile.qiec_ir",
    "IRQiecTypeKind": "quivers.transpile.qiec_ir",
    "IRQiecTypeVariable": "quivers.transpile.qiec_ir",
    "IRQiecUserIndexSort": "quivers.transpile.qiec_ir",
    "IRQiecValue": "quivers.transpile.qiec_ir",
    "IRQiecValueExpr": "quivers.transpile.ir",
    "IRQiecVar": "quivers.transpile.qiec_ir",
    "IRQiecWeightSum": "quivers.transpile.qiec_ir",
    "IRReturn": "quivers.transpile.ir",
    "IRSample": "quivers.transpile.ir",
    "IRScore": "quivers.transpile.ir",
    "LetAffineSource": "quivers.transpile.ir",
    "LetExprAffineMap": "quivers.transpile.ir",
    "Lower": "quivers.transpile.plan",
    "MarginalizeAtomSet": "quivers.transpile.family_meta",
    "MarginalizeSupport": "quivers.transpile.family_meta",
    "OverOrCodomainAxes": "quivers.transpile.ir",
    "Plate": "quivers.transpile.ir",
    "QiecCapabilityDiagnostic": "quivers.transpile.qiec_ir",
    "QiecFeature": "quivers.transpile.qiec_ir",
    "QiecTargetCapabilities": "quivers.transpile.qiec_ir",
    "RendererDuplicateError": "quivers.transpile.renderer_registry",
    "RendererLookupError": "quivers.transpile.renderer_registry",
    "StructuredArgSpec": "quivers.transpile.ir",
    "StructuredDataArg": "quivers.transpile.ir",
    "StructuredKernelArg": "quivers.transpile.ir",
    "StructuredSampleLowering": "quivers.transpile.ir",
    "StructuredZeroVectorArg": "quivers.transpile.ir",
    "TARGET_NAME_SEPARATOR": "quivers.transpile.plan",
    "affine_column_offsets": "quivers.transpile.ir",
    "affine_domain_width": "quivers.transpile.ir",
    "analyze_qiec_capabilities": "quivers.transpile.qiec_ir",
    "available_targets": "quivers.transpile._entry",
    "bridge_source": "quivers.transpile.family_spelling",
    "can_spell": "quivers.transpile.family_spelling",
    "capabilities_for_target": "quivers.transpile.qiec_ir",
    "checked_module": "quivers.transpile.plan",
    "checked_program_plan": "quivers.transpile.plan",
    "class_index_outcome": "quivers.transpile.family_meta",
    "emit_hook": "quivers.transpile.renderer_registry",
    "event_dim_of": "quivers.transpile.ir",
    "event_shape_of": "quivers.transpile.ir",
    "finite_enumerable_at_call_site": "quivers.transpile.family_meta",
    "from_constraint": "quivers.transpile.ir",
    "get_emit": "quivers.transpile.renderer_registry",
    "helper_families": "quivers.transpile.family_spelling",
    "helper_roots": "quivers.transpile.family_spelling",
    "host_runtime_capability_diagnostics": "quivers.transpile.qiec_ir",
    "is_int_bit": "quivers.transpile.ir",
    "is_int_category": "quivers.transpile.ir",
    "is_int_count": "quivers.transpile.ir",
    "is_real_bounded_interval": "quivers.transpile.ir",
    "is_real_corr_chol": "quivers.transpile.ir",
    "is_real_cov_matrix": "quivers.transpile.ir",
    "is_real_matrix": "quivers.transpile.ir",
    "is_real_one_hot": "quivers.transpile.ir",
    "is_real_positive": "quivers.transpile.ir",
    "is_real_scalar": "quivers.transpile.ir",
    "is_real_simplex": "quivers.transpile.ir",
    "is_real_unit_interval": "quivers.transpile.ir",
    "is_real_vector": "quivers.transpile.ir",
    "lower_qiec_ir": "quivers.transpile.qiec_ir",
    "marginalize_support": "quivers.transpile.family_meta",
    "parser_registry": "quivers.transpile._pipeline",
    "program_plan": "quivers.transpile.plan",
    "real_interval_bounds": "quivers.transpile.ir",
    "registered_backends": "quivers.transpile.renderer_registry",
    "registered_node_types": "quivers.transpile.renderer_registry",
    "spell_distribution": "quivers.transpile.family_spelling",
    "target_name": "quivers.transpile.plan",
    "target_protocol": "quivers.transpile._pipeline",
    "transpile": "quivers.transpile._entry",
    "unregister": "quivers.transpile.renderer_registry",
    "unsupported_for": "quivers.transpile._support",
}


type _LazyExport = (
    type
    | types.FunctionType
    | types.GenericAlias
    | TypeAliasType
    | frozenset[str]
    | dict[str, str]
    | dict[str, FamilyMeta]
    | str
)


def __getattr__(name: str) -> _LazyExport:
    """Bind a public name of a leaf module on first access.

    Parameters
    ----------
    name : str
        The attribute requested.

    Returns
    -------
    _LazyExport
        The object the defining module binds under that name.

    Raises
    ------
    AttributeError
        If ``name`` is not a lazily bound export.
    """
    home = _LAZY_EXPORTS.get(name)
    if home is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value: _LazyExport = getattr(importlib.import_module(home), name)
    globals()[name] = value
    return value


__all__ = [
    "Backend",
    "BackendRenderer",
    "CATEGORICAL_METADATA_IGNORABLE",
    "CHURCH_LIKE",
    "CSBoolean",
    "CSCorrCholesky",
    "CSIntegerInterval",
    "CSInterval",
    "CSLowerCholesky",
    "CSNonnegativeInteger",
    "CSOneHot",
    "CSPositive",
    "CSPositiveDefinite",
    "CSPositiveInteger",
    "CSReal",
    "CSRealMatrix",
    "CSRealVector",
    "CSSimplex",
    "CSUnitInterval",
    "ClassIndexOutcome",
    "ConstraintSpec",
    "DYNAMIC_TARGET_LANGUAGES",
    "Dim",
    "DimDynamic",
    "DimStatic",
    "DistributionSpelling",
    "DomainGridAxis",
    "EmitFn",
    "EmitPretty",
    "EventAxisSource",
    "FAMILY_META",
    "FamilyMeta",
    "IRArg",
    "IRArgBroadcast",
    "IRArgFamilyRef",
    "IRArgKernel",
    "IRArgList",
    "IRArgMatrix",
    "IRArgNumber",
    "IRArgRef",
    "IRCall",
    "IRDataInput",
    "IRDeterministic",
    "IRMarginalize",
    "IRNode",
    "IRObserve",
    "IRProgram",
    "IRQiecAffineMap",
    "IRQiecArgumentDef",
    "IRQiecArrowKind",
    "IRQiecAttachmentRef",
    "IRQiecBind",
    "IRQiecBindStep",
    "IRQiecBinder",
    "IRQiecBoolLiteral",
    "IRQiecBranchGiven",
    "IRQiecBytesLiteral",
    "IRQiecCall",
    "IRQiecCase",
    "IRQiecCaseBranch",
    "IRQiecCaseMotive",
    "IRQiecComprehension",
    "IRQiecComputation",
    "IRQiecComputationType",
    "IRQiecConstructorDecl",
    "IRQiecConstructorValue",
    "IRQiecContextSort",
    "IRQiecDistributionValue",
    "IRQiecDynamicAddressFrame",
    "IRQiecEffectBinder",
    "IRQiecEffectDef",
    "IRQiecEffectKind",
    "IRQiecEffectRef",
    "IRQiecEffectRequest",
    "IRQiecEffectRow",
    "IRQiecEffectVariable",
    "IRQiecEqualityType",
    "IRQiecEvidence",
    "IRQiecEvidenceValue",
    "IRQiecFamilyDecl",
    "IRQiecFieldDef",
    "IRQiecFloatLiteral",
    "IRQiecFunctionType",
    "IRQiecGather",
    "IRQiecHandle",
    "IRQiecHandlerClauseDef",
    "IRQiecHandlerDef",
    "IRQiecHandlerReturnClauseDef",
    "IRQiecId",
    "IRQiecIf",
    "IRQiecIndexBinder",
    "IRQiecIndexConstructor",
    "IRQiecIndexLiteral",
    "IRQiecIndexSort",
    "IRQiecIndexVariable",
    "IRQiecIntLiteral",
    "IRQiecKernelMatrix",
    "IRQiecKind",
    "IRQiecLiteral",
    "IRQiecLiteralValue",
    "IRQiecLocal",
    "IRQiecLogDensity",
    "IRQiecModule",
    "IRQiecNamedArgument",
    "IRQiecNamedComputation",
    "IRQiecNamedEffectInstance",
    "IRQiecNatSort",
    "IRQiecNewInstance",
    "IRQiecNullLiteral",
    "IRQiecOperationDef",
    "IRQiecPerform",
    "IRQiecPlateAxis",
    "IRQiecPlateShape",
    "IRQiecPrimitiveApplication",
    "IRQiecProgramEntry",
    "IRQiecProgramParameter",
    "IRQiecProgramSite",
    "IRQiecProjection",
    "IRQiecReduction",
    "IRQiecReflexivity",
    "IRQiecResume",
    "IRQiecReturn",
    "IRQiecRowEntry",
    "IRQiecRowKind",
    "IRQiecRowVariable",
    "IRQiecRowwise",
    "IRQiecSegmentSum",
    "IRQiecShapeIndex",
    "IRQiecShapeSort",
    "IRQiecSiteProvenance",
    "IRQiecSiteValue",
    "IRQiecSourceOrigin",
    "IRQiecStatic",
    "IRQiecStringLiteral",
    "IRQiecTableMap",
    "IRQiecTensorValue",
    "IRQiecTransportValue",
    "IRQiecTupleLiteral",
    "IRQiecTupleValue",
    "IRQiecTypeApplication",
    "IRQiecTypeBinder",
    "IRQiecTypeConstructor",
    "IRQiecTypeKind",
    "IRQiecTypeVariable",
    "IRQiecUserIndexSort",
    "IRQiecValue",
    "IRQiecValueExpr",
    "IRQiecVar",
    "IRQiecWeightSum",
    "IRReturn",
    "IRSample",
    "IRScore",
    "LetAffineSource",
    "LetExprAffineMap",
    "Lower",
    "MarginalizeAtomSet",
    "MarginalizeSupport",
    "OverOrCodomainAxes",
    "PYTHON_DEEP",
    "Plate",
    "QIEC_SURFACE",
    "QiecCapabilityDiagnostic",
    "QiecFeature",
    "QiecTargetCapabilities",
    "RefusedDeclaration",
    "RendererDuplicateError",
    "RendererLookupError",
    "STAN_LIKE",
    "StructuredArgSpec",
    "StructuredDataArg",
    "StructuredKernelArg",
    "StructuredSampleLowering",
    "StructuredZeroVectorArg",
    "TARGET_NAME_SEPARATOR",
    "UnsupportedConstruct",
    "affine_column_offsets",
    "affine_domain_width",
    "analyze_qiec_capabilities",
    "available_targets",
    "bridge_source",
    "can_spell",
    "capabilities_for_target",
    "checked_module",
    "checked_program_plan",
    "class_index_outcome",
    "emit_hook",
    "event_dim_of",
    "event_shape_of",
    "finite_enumerable_at_call_site",
    "from_constraint",
    "get_emit",
    "helper_families",
    "helper_roots",
    "host_runtime_capability_diagnostics",
    "is_int_bit",
    "is_int_category",
    "is_int_count",
    "is_real_bounded_interval",
    "is_real_corr_chol",
    "is_real_cov_matrix",
    "is_real_matrix",
    "is_real_one_hot",
    "is_real_positive",
    "is_real_scalar",
    "is_real_simplex",
    "is_real_unit_interval",
    "is_real_vector",
    "lower_qiec_ir",
    "marginalize_support",
    "parser_registry",
    "program_plan",
    "real_interval_bounds",
    "registered_backends",
    "registered_node_types",
    "spell_distribution",
    "target_name",
    "target_protocol",
    "transpile",
    "unregister",
    "unsupported_for",
]
