(define (_qvr-qiec-get container key . rest)
  ;; Only an association list holds keys; a tuple's item list or any
  ;; other list answers with the default rather than failing in assoc.
  (let ((entry (and (_qvr-qiec-alist? container) (assoc key container))))
    (if entry (cdr entry) (if (pair? rest) (car rest) #f))))
(define (_qvr-qiec-set container key value)
  (cons (cons key value)
        (filter (lambda (entry) (not (equal? (car entry) key))) container)))
(define (_qvr-qiec-pure value) (list 'pure value))
;; A deferred computation. Calls are forced by the trampolines in _qvr-qiec-run and
;; the handler walk rather than when they are built, so a recursive QIEC computation
;; does not consume host stack per call. The frames are the dynamic address frames the
;; result runs under, and the tail flag records that the call retires the frame of the
;; computation that made it.
(define (_qvr-qiec-call thunk . rest)
  (let ((frames (if (pair? rest) (car rest) '()))
        (tail (and (pair? rest) (pair? (cdr rest)) (cadr rest))))
    (list 'call thunk frames tail)))
(define (_qvr-qiec-join-frames outer inner tail)
  (if (and tail (pair? outer) (equal? (car (list-ref outer (- (length outer) 1))) "call"))
      (append (list-head outer (- (length outer) 1)) inner)
      (append outer inner)))
(define (_qvr-qiec-scoped computation frames)
  (cond
    ((or (null? frames) (eq? (car computation) 'pure)) computation)
    ((eq? (car computation) 'call)
     (list 'call (cadr computation)
           (_qvr-qiec-join-frames frames (caddr computation) (cadddr computation))
           #f))
    ((eq? (car computation) 'bind)
     (list 'bind (_qvr-qiec-scoped (cadr computation) frames)
           (lambda (value) (_qvr-qiec-scoped ((caddr computation) value) frames))
           (cadddr computation)))
    (else
     (let* ((request (cadr computation))
            (address (_qvr-qiec-get request "address"))
            (updated (list (car address) (append frames (cadr address)) (caddr address))))
       (list 'effect (_qvr-qiec-set request "address" updated)
             (lambda (value) (_qvr-qiec-scoped ((caddr computation) value) frames)))))))
;; The trampoline. Deferred calls are forced and deferred binds are unfolded onto an
;; explicit continuation stack, so however deep a recursion is, the host stack stays
;; flat. A request surfacing beneath pending binds carries them in its continuation,
;; and their captures, so a multi-shot resumption still sees everything it copies.
(define (_qvr-qiec-force computation . rest)
  (let loop ((current computation) (stack (if (pair? rest) (car rest) '())))
    (cond
      ((eq? (car current) 'call)
       (loop (_qvr-qiec-scoped ((cadr current)) (caddr current)) stack))
      ((eq? (car current) 'bind)
       (loop (cadr current) (cons (cons (caddr current) (cadddr current)) stack)))
      ((eq? (car current) 'pure)
       (if (null? stack)
           current
           (loop ((caar stack) (cadr current)) (cdr stack))))
      (else
       (if (null? stack)
           current
           (let* ((request (cadr current))
                  (captures (apply append (_qvr-qiec-get request "captures" '())
                                   (map cdr stack)))
                  (resume-effect (caddr current)))
             (list 'effect (_qvr-qiec-set request "captures" captures)
                   (lambda (value) (_qvr-qiec-force (resume-effect value) stack)))))))))
(define _qvr-qiec-call-serial 0)
(define _qvr-qiec-instance-serial 0)
(define (_qvr-qiec-enter-call name thunk tail)
  (set! _qvr-qiec-call-serial (+ _qvr-qiec-call-serial 1))
  (_qvr-qiec-call thunk
                  (list (list "call" (string-append name "#" (number->string _qvr-qiec-call-serial))))
                  tail))
(define (_qvr-qiec-instance thunk)
  (set! _qvr-qiec-instance-serial (+ _qvr-qiec-instance-serial 1))
  (_qvr-qiec-call thunk (list (list "instance" _qvr-qiec-instance-serial)) #f))
(define (_qvr-qiec-resume resume value) (_qvr-qiec-as-computation (resume value)))
(define (_qvr-qiec-if condition then otherwise)
  (let ((flag (_qvr-qiec-value condition)))
    (if (not (boolean? flag)) (error 'qiec "QIEC if condition is not a Boolean"))
    (if flag (then) (otherwise))))
;; The closed primitive table. Names and semantics mirror the kernel registry;
;; integer division and remainder truncate toward zero on every host.
(define _qvr-qiec-primitives
  (list
    (cons "add_int" +)
    (cons "sub_int" -)
    (cons "mul_int" *)
    (cons "div_int" quotient)
    (cons "mod_int" remainder)
    (cons "neg_int" (lambda (a) (- a)))
    (cons "abs_int" abs)
    (cons "min_int" min)
    (cons "max_int" max)
    (cons "add_real" +)
    (cons "sub_real" -)
    (cons "mul_real" *)
    (cons "div_real" (lambda (a b) (/ (exact->inexact a) b)))
    (cons "neg_real" (lambda (a) (- a)))
    (cons "abs_real" abs)
    (cons "min_real" min)
    (cons "max_real" max)
    (cons "pow_real" (lambda (a b) (expt (exact->inexact a) b)))
    (cons "exp" exp)
    (cons "log" log)
    (cons "sqrt" (lambda (a) (sqrt (exact->inexact a))))
    (cons "eq_int" =)
    (cons "ne_int" (lambda (a b) (not (= a b))))
    (cons "lt_int" <)
    (cons "le_int" <=)
    (cons "gt_int" >)
    (cons "ge_int" >=)
    (cons "eq_real" =)
    (cons "ne_real" (lambda (a b) (not (= a b))))
    (cons "lt_real" <)
    (cons "le_real" <=)
    (cons "gt_real" >)
    (cons "ge_real" >=)
    (cons "eq_bool" eq?)
    (cons "ne_bool" (lambda (a b) (not (eq? a b))))
    (cons "eq_string" string=?)
    (cons "ne_string" (lambda (a b) (not (string=? a b))))
    (cons "and" (lambda (a b) (and a b)))
    (cons "or" (lambda (a b) (or a b)))
    (cons "not" not)
    (cons "concat" string-append)
    (cons "int_to_real" exact->inexact)
    (cons "int_to_string" number->string)
    (cons "real_to_int" (lambda (a) (exact (truncate a))))
    (cons "expm1" (lambda (a) (- (exp a) 1.0)))
    (cons "log1p" (lambda (a) (log (+ 1.0 a))))
    (cons "log2" (lambda (a) (/ (log a) (log 2.0))))
    (cons "log10" (lambda (a) (/ (log a) (log 10.0))))
    (cons "rsqrt" (lambda (a) (/ 1.0 (sqrt a))))
    (cons "square" (lambda (a) (* a a)))
    (cons "sign" (lambda (a) (cond ((> a 0.0) 1.0) ((< a 0.0) -1.0) (else 0.0))))
    (cons "reciprocal" (lambda (a) (/ 1.0 a)))
    (cons "sin" sin)
    (cons "cos" cos)
    (cons "tan" tan)
    (cons "asin" asin)
    (cons "acos" acos)
    (cons "atan" atan)
    (cons "sinh" (lambda (a) (/ (- (exp a) (exp (- a))) 2.0)))
    (cons "cosh" (lambda (a) (/ (+ (exp a) (exp (- a))) 2.0)))
    (cons "tanh" (lambda (a) (let ((e (exp (* 2.0 a)))) (/ (- e 1.0) (+ e 1.0)))))
    (cons "asinh" (lambda (a) (log (+ a (sqrt (+ (* a a) 1.0))))))
    (cons "acosh" (lambda (a) (log (+ a (sqrt (- (* a a) 1.0))))))
    (cons "atanh" (lambda (a) (* 0.5 (log (/ (+ 1.0 a) (- 1.0 a))))))
    (cons "floor" (lambda (a) (exact->inexact (floor a))))
    (cons "ceil" (lambda (a) (exact->inexact (ceiling a))))
    (cons "round" (lambda (a) (exact->inexact (round a))))
    (cons "trunc" (lambda (a) (exact->inexact (truncate a))))
    (cons "erf" (lambda (a) (_qvr-qiec-erf (exact->inexact a))))
    (cons "erfc" (lambda (a) (- 1.0 (_qvr-qiec-erf (exact->inexact a)))))
    (cons "erfinv" (lambda (a) (_qvr-qiec-erfinv (exact->inexact a))))
    (cons "lgamma" (lambda (a) (_qvr-qiec-lgamma (exact->inexact a))))
    (cons "digamma" (lambda (a) (_qvr-qiec-digamma (exact->inexact a))))
    (cons "sigmoid" (lambda (a) (_qvr-qiec-sigmoid (exact->inexact a))))
    (cons "relu" (lambda (a) (max a 0.0)))
    (cons "relu6" (lambda (a) (min (max a 0.0) 6.0)))
    (cons "elu" (lambda (a) (if (> a 0.0) a (- (exp a) 1.0))))
    (cons "selu" (lambda (a) (* 1.0507009873554805 (if (> a 0.0) a (* 1.6732632423543772 (- (exp a) 1.0))))))
    (cons "gelu" (lambda (a) (* 0.5 a (+ 1.0 (_qvr-qiec-erf (/ a (sqrt 2.0)))))))
    (cons "silu" (lambda (a) (* a (_qvr-qiec-sigmoid (exact->inexact a)))))
    (cons "mish" (lambda (a) (* a (let ((e (exp (* 2.0 (_qvr-qiec-softplus (exact->inexact a)))))) (/ (- e 1.0) (+ e 1.0))))))
    (cons "softplus" (lambda (a) (_qvr-qiec-softplus (exact->inexact a))))
    (cons "logsigmoid" (lambda (a) (- (_qvr-qiec-softplus (- (exact->inexact a))))))
    (cons "softsign" (lambda (a) (/ a (+ 1.0 (abs a)))))
    (cons "as_weight" exact->inexact)
    (cons "weight_value" exact->inexact)
    (cons "add_weight" +)
    (cons "scale_weight" *)))
(define (_qvr-qiec-sigmoid value)
  (if (>= value 0.0)
      (/ 1.0 (+ 1.0 (exp (- value))))
      (let ((e (exp value))) (/ e (+ 1.0 e)))))
(define (_qvr-qiec-softplus value)
  (+ (max value 0.0) (log (+ 1.0 (exp (- (abs value)))))))
;; The error function by its Taylor series near the origin and by the
;; continued fraction of the complementary function in the tails.
(define (_qvr-qiec-erf value)
  (let ((sign (if (< value 0.0) -1.0 1.0)) (x (abs value)))
    (if (< x 2.5)
        (let loop ((term x) (total x) (n 0))
          (if (or (<= (abs term) (* 1e-17 (abs total))) (>= n 200))
              (* sign (/ 2.0 (sqrt 3.141592653589793)) total)
              (let* ((n2 (+ n 1)) (term2 (* term (/ (- (* x x)) n2))))
                (loop term2 (+ total (/ term2 (+ (* 2 n2) 1))) n2))))
        (let loop ((k 60) (fraction x))
          (if (= k 0)
              (* sign (- 1.0 (/ (exp (- (* x x))) (sqrt 3.141592653589793) fraction)))
              (loop (- k 1) (+ x (/ (/ k 2.0) fraction))))))))
(define (_qvr-qiec-erfinv value)
  (cond
    ((or (< value -1.0) (> value 1.0)) (error 'qiec "erfinv is defined on [-1, 1]"))
    ((= value 1.0) +inf.0)
    ((= value -1.0) -inf.0)
    ((= value 0.0) 0.0)
    (else
     (let* ((sign (if (> value 0.0) 1.0 -1.0))
            (magnitude (abs value))
            (estimate
             (if (< magnitude 0.7)
                 (let ((square (* magnitude magnitude)))
                   (/ (* magnitude (+ (* (- (* (+ (* -0.140543331 square) 0.914624893) square) 1.645349621) square) 0.886226899))
                      (+ (* (+ (* (- (* (+ (* 0.012229801 square) -0.329097515) square) -1.442710462) square) -2.118377725) square) 1.0)))
                 (let ((tail (sqrt (- (log (/ (- 1.0 magnitude) 2.0))))))
                   (/ (- (* (- (* (+ (* 1.641345311 tail) 3.429567803) tail) 1.62490649) tail) 1.970840454)
                      (+ (* (+ (* 1.637067800 tail) 3.543889200) tail) 1.0))))))
       (let loop ((i 0) (estimate estimate))
         (if (= i 3)
             (* sign estimate)
             (loop (+ i 1)
                   (- estimate (/ (- (_qvr-qiec-erf estimate) magnitude)
                                  (* (/ 2.0 (sqrt 3.141592653589793)) (exp (- (* estimate estimate)))))))))))))
;; Lanczos approximation of log gamma.
(define (_qvr-qiec-lgamma value)
  (if (< value 0.5)
      (- (log (/ 3.141592653589793 (abs (sin (* 3.141592653589793 value))))) (_qvr-qiec-lgamma (- 1.0 value)))
      (let* ((coefficients '(676.5203681218851 -1259.1392167224028 771.32342877765313 -176.61502916214059 12.507343278686905 -0.13857109526572012 9.9843695780195716e-6 1.5056327351493116e-7))
             (x (- value 1.0))
             (total (let loop ((items coefficients) (i 1) (acc 0.99999999999980993))
                      (if (null? items) acc (loop (cdr items) (+ i 1) (+ acc (/ (car items) (+ x i)))))))
             (t (+ x 7.5)))
        (+ (* 0.5 (log (* 2.0 3.141592653589793))) (* (+ x 0.5) (log t)) (- t) (log total)))))
(define (_qvr-qiec-digamma value)
  (cond
    ((and (<= value 0.0) (= value (floor value))) (error 'qiec "digamma has a pole at nonpositive integers"))
    ((< value 0.0) (- (_qvr-qiec-digamma (- 1.0 value)) (/ 3.141592653589793 (tan (* 3.141592653589793 value)))))
    (else
     (let loop ((v value) (result 0.0))
       (if (< v 6.0)
           (loop (+ v 1.0) (- result (/ 1.0 v)))
           (let* ((inverse (/ 1.0 v)) (square (* inverse inverse)))
             (+ result (log v) (- (* 0.5 inverse))
                (- (* square (- (/ 1.0 12.0) (* square (- (/ 1.0 120.0) (* square (- (/ 1.0 252.0) (* square (- (/ 1.0 240.0) (/ square 132.0)))))))))))))))))
;; A tensor reaches a primitive either as its tuple record or, once read
;; through a binding, as the record's item list; neither is an
;; association list, which is how a constructor or evidence record looks.
(define (_qvr-qiec-tensor? value)
  (and (pair? value)
       (or (equal? (_qvr-qiec-get value "qiec" #f) "tuple")
           (not (_qvr-qiec-alist? value)))))
(define (_qvr-qiec-items value)
  (if (and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "tuple"))
      (_qvr-qiec-get value "items" '())
      value))
(define (_qvr-qiec-broadcast implementation arguments)
  (let ((tensors (filter _qvr-qiec-tensor? arguments)))
    (if (null? tensors)
        (apply implementation arguments)
        (let ((len (length (_qvr-qiec-items (car tensors)))))
          (if (not (for-all (lambda (tensor) (= (length (_qvr-qiec-items tensor)) len)) tensors))
              (error 'qiec "QIEC primitive applied to tensors of differing shapes"))
          (_qvr-qiec-tuple
            (let loop ((index 0))
              (if (= index len)
                  '()
                  (cons (_qvr-qiec-broadcast implementation
                                             (map (lambda (argument)
                                                    (if (_qvr-qiec-tensor? argument)
                                                        (list-ref (_qvr-qiec-items argument) index)
                                                        argument))
                                                  arguments))
                        (loop (+ index 1))))))))))
(define (_qvr-qiec-primitive name arguments)
  (let ((entry (assoc name _qvr-qiec-primitives)))
    (if (not entry) (error 'qiec "unknown QIEC primitive" name))
    (_qvr-qiec-broadcast (cdr entry) (map _qvr-qiec-raw arguments))))
(define (_qvr-qiec-raw value)
  (if (_qvr-qiec-binding? value) (vector-ref (_qvr-qiec-get value "cell") 0) value))
(define (_qvr-qiec-gather value index)
  (let ((items (_qvr-qiec-value value)) (index (_qvr-qiec-value index)))
    (if (not (list? items)) (error 'qiec "QIEC gather from a non-tensor runtime value"))
    (if (list? index)
        (_qvr-qiec-tuple (map (lambda (item) (_qvr-qiec-gather value item)) index))
        (list-ref items index))))
(define (_qvr-qiec-flat value)
  (let ((value (_qvr-qiec-value value)))
    (if (list? value)
        (apply append (map _qvr-qiec-flat value))
        (list value))))
(define (_qvr-qiec-reduce operator value)
  (let* ((entries (_qvr-qiec-flat value)) (total (apply + entries)))
    (cond
      ((string=? operator "sum") total)
      ((string=? operator "mean") (/ total (length entries)))
      ((string=? operator "max") (apply max entries))
      ((string=? operator "min") (apply min entries))
      ((string=? operator "prod") (apply * entries))
      (else (let ((peak (apply max entries)))
              (+ peak (log (apply + (map (lambda (entry) (exp (- entry peak))) entries)))))))))
(define (_qvr-qiec-rowwise operator value)
  (let ((row (_qvr-qiec-value value)))
    (if (and (pair? row) (_qvr-qiec-tensor? (car row)))
        (_qvr-qiec-tuple (map (lambda (item) (_qvr-qiec-rowwise operator item)) row))
        (let ((row (map exact->inexact row)))
          (_qvr-qiec-tuple
            (cond
              ((string=? operator "softmax")
               (let* ((peak (apply max row))
                      (weights (map (lambda (item) (exp (- item peak))) row))
                      (total (apply + weights)))
                 (map (lambda (weight) (/ weight total)) weights)))
              ((string=? operator "log_softmax")
               (let* ((peak (apply max row))
                      (normalizer (+ peak (log (apply + (map (lambda (item) (exp (- item peak))) row))))))
                 (map (lambda (item) (- item normalizer)) row)))
              ((string=? operator "cumsum")
               (let loop ((items row) (running 0.0) (acc '()))
                 (if (null? items)
                     (reverse acc)
                     (let ((next (+ running (car items))))
                       (loop (cdr items) next (cons next acc))))))
              ((string=? operator "sort") (list-sort < row))
              (else (let ((total (apply + row))) (map (lambda (item) (/ item total)) row)))))))))
(define (_qvr-qiec-weight-sum value) (apply + (_qvr-qiec-flat value)))
(define (_qvr-qiec-segment-sum value index groups)
  (let ((totals (make-vector groups 0.0)))
    (for-each (lambda (weight group) (vector-set! totals group (+ (vector-ref totals group) weight)))
              (_qvr-qiec-value value) (_qvr-qiec-value index))
    (_qvr-qiec-tuple (vector->list totals))))
(define (_qvr-qiec-project value position)
  (let ((items (_qvr-qiec-value value)))
    (if (or (not (list? items)) (>= position (length items)))
        (error 'qiec "QIEC projection from a non-product runtime value"))
    (list-ref items position)))
(define _qvr-qiec-authored '())
(define (_qvr-qiec-register-authored handler-id handler)
  (set! _qvr-qiec-authored (_qvr-qiec-set _qvr-qiec-authored handler-id handler)))
(define (_qvr-qiec-member container key)
  (_qvr-qiec-get container key #f))
(define (_qvr-qiec-static-kind argument)
  (let ((kind (_qvr-qiec-get argument "kind" #f)))
    (cond
      ((member kind '("type-variable" "type-application" "function-type" "equality-type")) "type")
      ((member kind '("effect-variable" "effect-ref")) "effect")
      (else "index"))))
(define (_qvr-qiec-static-environment telescope arguments)
  (let ((ordered
          (cond
            ((not arguments) '())
            ((and (pair? arguments) (string? (caar arguments)))
             (map (lambda (binder)
                    (let ((entry (assoc (_qvr-qiec-get binder "name") arguments)))
                      (if entry (cdr entry) (error 'qiec "QIEC static arguments do not match the checked telescope"))))
                  telescope))
            (else arguments))))
    (if (not (= (length ordered) (length telescope)))
        (error 'qiec "QIEC static argument arity does not match the checked telescope"))
    (map (lambda (binder argument)
           (if (not (equal? (_qvr-qiec-static-kind argument)
                            (_qvr-qiec-get binder "kind")))
               (error 'qiec "QIEC static argument kind does not match the checked telescope"))
           (cons (_qvr-qiec-get binder "name") argument))
         telescope ordered)))
(define (_qvr-qiec-alist? value)
  (and (pair? value)
       (for-all (lambda (item) (and (pair? item) (string? (car item)))) value)))
(define (_qvr-qiec-specialize value environment)
  (cond
    ((_qvr-qiec-alist? value)
     (let ((kind (_qvr-qiec-get value "kind" #f))
           (identity (_qvr-qiec-get value "identity" '()))
           (name (_qvr-qiec-get value "name" #f)))
       (if (and (member kind '("type-variable" "index-variable" "effect-variable"))
                (assoc (if (null? identity) name identity) environment))
           (cdr (assoc (if (null? identity) name identity) environment))
           (map (lambda (entry)
                  (cons (car entry) (_qvr-qiec-specialize (cdr entry) environment)))
                value))))
    ((pair? value) (map (lambda (item) (_qvr-qiec-specialize item environment)) value))
    (else value)))
(define _qvr-qiec-ambient-handlers (make-parameter '()))
(define (_qvr-qiec-unique items)
  (let loop ((remaining items) (result '()))
    (if (null? remaining)
        (reverse result)
        (loop (cdr remaining)
              (if (exists (lambda (item) (eq? item (car remaining))) result)
                  result
                  (cons (car remaining) result))))))
(define (_qvr-qiec-with-ambient controller thunk)
  (parameterize ((_qvr-qiec-ambient-handlers
                   (append (_qvr-qiec-ambient-handlers) (list controller))))
    (thunk)))
(define (_qvr-qiec-effect request static-environment)
  (set! request (_qvr-qiec-specialize request static-environment))
  (let ((controllers
          (_qvr-qiec-unique
            (append (_qvr-qiec-get request "handler_captures" '())
                    (_qvr-qiec-ambient-handlers)))))
    (set! request (_qvr-qiec-set request "captures"
                    (_qvr-qiec-get request "captures" '())))
    (set! request (_qvr-qiec-set request "handler_captures" controllers))
    (set! request (_qvr-qiec-set request "handler_states"
                    (map (lambda (controller)
                           ((_qvr-qiec-get controller "capture")))
                         controllers)))
    (list 'effect request _qvr-qiec-pure)))
(define (_qvr-qiec-bind computation continuation . capture-rest)
  (let ((captures (if (pair? capture-rest) (car capture-rest) '())))
    (cond
      ((eq? (car computation) 'pure)
        (continuation (cadr computation)))
      ((or (eq? (car computation) 'call) (eq? (car computation) 'bind))
        (list 'bind computation continuation captures))
      (else
        (let ((request (_qvr-qiec-set
                         (cadr computation)
                         "captures"
                         (append (_qvr-qiec-get (cadr computation) "captures" '()) captures))))
          (list 'effect request
                (lambda (value)
                  (_qvr-qiec-bind ((caddr computation) value) continuation captures))))))))
(define (_qvr-qiec-binding? value)
  (and (pair? value)
       (equal? (_qvr-qiec-get value "qiec" #f) "binding")
       (_qvr-qiec-get value "cell" #f)))
(define (_qvr-qiec-value value)
  (cond
    ((_qvr-qiec-binding? value) (vector-ref (_qvr-qiec-get value "cell") 0))
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "tuple"))
     (_qvr-qiec-get value "items" '()))
    (else value)))
(define (_qvr-qiec-tuple items)
  (list (cons "qiec" "tuple") (cons "items" items)))
(define (_qvr-qiec-constructor constructor static-arguments fields result-type static-environment)
  (list (cons "qiec" "constructor")
        (cons "constructor" constructor)
        (cons "static_arguments" (_qvr-qiec-specialize static-arguments static-environment))
        (cons "fields" fields)
        (cons "result_type" (_qvr-qiec-specialize result-type static-environment))))
(define (_qvr-qiec-evidence evidence static-environment)
  (list (cons "qiec" "evidence")
        (cons "evidence" (_qvr-qiec-specialize evidence static-environment))))
(define (_qvr-qiec-transport evidence value target-type static-environment)
  (_qvr-qiec-specialize evidence static-environment)
  (_qvr-qiec-specialize target-type static-environment)
  value)
(define (_qvr-qiec-attachment attachments attachment expected-type static-environment)
  (let ((entry (assoc attachment attachments)))
    (if (not entry) (error 'qiec "missing QIEC attachment" attachment))
    (let ((binding (cdr entry)))
      (if (or (not (_qvr-qiec-binding? binding))
              (not (assoc "type" binding)))
          (error 'qiec "QIEC attachment must be a typed binding descriptor"))
      (set! expected-type (_qvr-qiec-specialize expected-type static-environment))
      (if (not (equal? (_qvr-qiec-get binding "type") expected-type))
          (error 'qiec "QIEC attachment type disagrees with checked IR"))
      (_qvr-qiec-value
        (_qvr-qiec-validate (_qvr-qiec-get binding "validator" #f)
                            binding
                            (string-append "attachment " attachment))))))
(define (_qvr-qiec-case value branches metadata static-environment)
  (set! metadata (_qvr-qiec-specialize metadata static-environment))
  (if (not (and (pair? value)
                (equal? (_qvr-qiec-get value "qiec" #f) "constructor")))
      (error 'qiec "QIEC case scrutinee is not a constructor value"))
  (let* ((constructor (_qvr-qiec-get value "constructor"))
         (admitted (assoc constructor (_qvr-qiec-get metadata "branches" '())))
         (branch (assoc constructor branches)))
    (if (not admitted) (error 'qiec "constructor is not admitted by the checked QIEC case"))
    (if branch
        (let* ((canonical (_qvr-qiec-get (cdr admitted) "static_arguments" '()))
               (actual (_qvr-qiec-get value "static_arguments" '()))
               (offset (- (length actual) (length canonical))))
          (if (< offset 0)
              (error 'qiec "QIEC constructor static arguments do not match case branch"))
          (let ((branch-environment
                  (append
                    (map (lambda (variable argument)
                           (let ((identity (_qvr-qiec-get variable "identity" '()))
                                 (name (_qvr-qiec-get variable "name" #f)))
                             (if (and (null? identity) (not name))
                                 (error 'qiec "QIEC case branch has an unbindable static variable"))
                             (cons (if (null? identity) name identity) argument)))
                         canonical
                         (list-tail actual offset))
                    static-environment)))
            (apply (cdr branch)
                   (cons branch-environment (_qvr-qiec-get value "fields" '())))))
        (error 'qiec "no QIEC case branch" constructor))))
(define (_qvr-qiec-as-computation value)
  (if (and (pair? value) (memq (car value) '(pure effect call bind)))
      value
      (_qvr-qiec-pure value)))
(define (_qvr-qiec-validate validator value label)
  (if (not validator)
      value
      (if (eq? (validator (_qvr-qiec-value value)) #f)
          (error 'qiec "QIEC runtime value failed" label)
          value)))
(define (_qvr-qiec-validate-computation computation validator label)
  (_qvr-qiec-bind
    (_qvr-qiec-as-computation computation)
    (lambda (value) (_qvr-qiec-pure (_qvr-qiec-validate validator value label)))))
(define (_qvr-qiec-capture locals attachment-ids attachments)
  (append
    (map (lambda (entry)
           (let ((binding (cdr entry)))
             (list (cons "kind" "local")
                   (cons "label" (car entry))
                   (cons "binding" binding)
                   (cons "seed"
                         (and (_qvr-qiec-binding? binding)
                              (vector (_qvr-qiec-value binding)))))))
         locals)
    (map (lambda (attachment)
           (let ((entry (assoc attachment attachments)))
             (if (not entry) (error 'qiec "missing QIEC attachment" attachment))
             (let ((binding (cdr entry)))
               (list (cons "kind" "attachment")
                     (cons "label" attachment)
                     (cons "binding" binding)
                     (cons "seed"
                           (and (_qvr-qiec-binding? binding)
                                (vector (_qvr-qiec-value binding))))))))
         attachment-ids)))
(define (_qvr-qiec-duplicable? value)
  (cond
    ((_qvr-qiec-binding? value) (eq? (_qvr-qiec-get value "duplicable" #f) #t))
    ((or (null? value) (boolean? value) (number? value) (string? value)) #t)
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "constructor"))
     (for-all _qvr-qiec-duplicable? (_qvr-qiec-get value "fields" '())))
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "evidence")) #t)
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "tuple"))
     (for-all _qvr-qiec-duplicable? (_qvr-qiec-get value "items" '())))
    (else #f)))
(define (_qvr-qiec-validate-capture request current-handler)
  (for-each
    (lambda (capture)
      (let ((binding (_qvr-qiec-get capture "binding"))
            (label (_qvr-qiec-get capture "label")))
        (if (not (_qvr-qiec-duplicable? binding))
            (error 'qiec "QIEC unrestricted resumption captures nonduplicable value" label))
        (if (and (_qvr-qiec-binding? binding)
                 (_qvr-qiec-get binding "mutable" #f)
                 (not (procedure? (_qvr-qiec-get binding "fork" #f))))
            (error 'qiec "QIEC mutable duplicable binding requires fork" label))))
    (_qvr-qiec-get request "captures" '()))
  (for-each
    (lambda (controller)
      ((_qvr-qiec-get controller "snapshot"))
      (let ((handler ((_qvr-qiec-get controller "get"))))
        (if (not (_qvr-qiec-get handler "duplicable_context" #f))
            (error 'qiec "QIEC unrestricted resumption captures nonduplicable handler context"))
        (if (and (_qvr-qiec-get handler "mutable_context" #f)
                 (not (procedure? (_qvr-qiec-get handler "fork_context" #f))))
            (error 'qiec "QIEC mutable duplicable handler context requires fork_context"))))
    (_qvr-qiec-unique
      (append (_qvr-qiec-get request "handler_captures" '())
              (list current-handler)))))
(define (_qvr-qiec-fork-capture request current-handler shot)
  (begin
        (for-each
          (lambda (capture)
            (let* ((binding (_qvr-qiec-get capture "binding"))
                   (fork (_qvr-qiec-get binding "fork" #f)))
              (if (and (_qvr-qiec-binding? binding) (procedure? fork))
                  (let ((cell (_qvr-qiec-get binding "cell"))
                        (seed (_qvr-qiec-get capture "seed")))
                    (vector-set! cell 0 (fork (vector-ref seed 0)))))))
          (_qvr-qiec-get request "captures" '()))
        (for-each
          (lambda (controller)
            ((_qvr-qiec-get controller "install_fork")))
          (_qvr-qiec-unique
            (append (_qvr-qiec-get request "handler_captures" '())
                    (list current-handler))))))
(define (_qvr-qiec-readdress computation shot)
  (set! computation (_qvr-qiec-force computation))
  (if (eq? (car computation) 'pure)
      computation
      (let* ((request (cadr computation))
             (address (_qvr-qiec-get request "address"))
             (updated (list (car address) (cadr address) (append (caddr address) (list shot))))
             (new-request (_qvr-qiec-set request "address" updated)))
        (list 'effect new-request
              (lambda (value) (_qvr-qiec-readdress ((caddr computation) value) shot))))))
(define (_qvr-qiec-same-members? left right)
  (and (= (length left) (length right))
       (for-all (lambda (item) (member item right)) left)))
(define (_qvr-qiec-validate-handler handler manifest)
  (let ((definition (_qvr-qiec-get handler "definition" #f))
        (structural (map (lambda (clause) (_qvr-qiec-get clause "operation"))
                         (_qvr-qiec-get manifest "clauses" '())))
        (executable (map car (_qvr-qiec-get handler "operations" '()))))
    (if (and definition (not (equal? definition manifest)))
        (error 'qiec "QIEC runtime handler definition disagrees with checked IR"))
    (if (not (_qvr-qiec-same-members? structural executable))
        (error 'qiec "QIEC runtime handler clauses disagree with checked IR"))
    (if (and (procedure? (_qvr-qiec-get handler "fork_context" #f))
             (not (_qvr-qiec-get handler "duplicable_context" #f)))
        (error 'qiec "QIEC handler fork_context requires duplicable_context"))
    (if (and (_qvr-qiec-get handler "mutable_context" #f)
             (_qvr-qiec-get handler "duplicable_context" #f)
             (not (procedure? (_qvr-qiec-get handler "fork_context" #f))))
        (error 'qiec "QIEC mutable duplicable handler requires fork_context"))))
(define (_qvr-qiec-lifecycle handler)
  (list (cons "handler" handler) (cons "finalized" (vector #f))))
(define (_qvr-qiec-lifecycle-exit lifecycle)
  (let ((state (_qvr-qiec-get lifecycle "finalized")))
    (if (not (vector-ref state 0))
        (begin
          (vector-set! state 0 #t)
          (let ((callback
                  (_qvr-qiec-get (_qvr-qiec-get lifecycle "handler")
                                 "on_exit" #f)))
            (if (procedure? callback) (callback)))))))
(define (_qvr-qiec-lifecycle-drop lifecycle)
  (let ((state (_qvr-qiec-get lifecycle "finalized")))
    (if (not (vector-ref state 0))
        (begin
          (vector-set! state 0 #t)
          (let ((callback
                  (_qvr-qiec-get (_qvr-qiec-get lifecycle "handler")
                                 "on_drop" #f)))
            (if (procedure? callback) (callback)))))))
(define (_qvr-qiec-lifecycle-enter handler)
  (let ((lifecycle (_qvr-qiec-lifecycle handler)))
    (guard (condition
             (else (_qvr-qiec-lifecycle-drop lifecycle) (raise condition)))
      (let ((callback (_qvr-qiec-get handler "on_enter" #f)))
        (if (procedure? callback) (callback))))
    lifecycle))
(define (_qvr-qiec-drop-request request)
  (for-each _qvr-qiec-lifecycle-drop
            (_qvr-qiec-get request "lifecycles" '())))
(define (_qvr-qiec-finalize computation lifecycle)
  (let ((current (_qvr-qiec-force (_qvr-qiec-as-computation computation))))
    (if (eq? (car current) 'pure)
        (begin (_qvr-qiec-lifecycle-exit lifecycle) current)
        (let ((request
                (_qvr-qiec-set
                  (cadr current) "lifecycles"
                  (append (_qvr-qiec-get (cadr current) "lifecycles" '())
                          (list lifecycle)))))
          (list 'effect request
                (lambda (value)
                  (_qvr-qiec-finalize ((caddr current) value) lifecycle)))))))
(define (_qvr-qiec-invoke entry . arguments)
  (apply (if (procedure? entry) entry (_qvr-qiec-get entry "invoke")) arguments))
(define (_qvr-qiec-handle computation instance manifest raw-static-arguments computation-static-environment handlers . rest)
  (let* ((static-arguments (_qvr-qiec-specialize raw-static-arguments computation-static-environment))
         (handler-static-environment
           (_qvr-qiec-static-environment
             (_qvr-qiec-get manifest "telescope" '()) static-arguments))
         (manifest (_qvr-qiec-set (_qvr-qiec-specialize manifest handler-static-environment) "telescope" '()))
         (attachments (if (pair? rest) (car rest) '()))
         (operations (if (and (pair? rest) (pair? (cdr rest))) (cadr rest) '()))
         (handler-id (_qvr-qiec-get manifest "id"))
         (handler-entry (or (assoc handler-id handlers)
                            (assoc handler-id _qvr-qiec-authored))))
    (if (not handler-entry) (error 'qiec "missing QIEC handler attachment" handler-id))
    (let* ((prototype (cdr handler-entry))
           (factory (_qvr-qiec-get prototype "context_factory" #f))
           (installed (if (procedure? factory) (factory) prototype))
           (checked
             (begin
               (if (and (eq? installed prototype)
                        (_qvr-qiec-get prototype "mutable_context" #f))
                   (error 'qiec "QIEC mutable handler requires context_factory"))
               (_qvr-qiec-validate-handler installed manifest)
               installed))
           (handler-ref (vector checked))
           (lifecycle-ref (vector (_qvr-qiec-lifecycle-enter checked)))
           (root-lifecycle (vector-ref lifecycle-ref 0))
           (seed-ref (vector checked))
           (controller
             (list (cons "get" (lambda () (vector-ref handler-ref 0)))
                   (cons "seed" (lambda () (vector-ref seed-ref 0)))
                   (cons "snapshot"
                         (lambda ()
                           (vector-set! seed-ref 0 (vector-ref handler-ref 0))))
                   (cons "capture"
                         (lambda ()
                           (list (vector-ref handler-ref 0)
                                 (vector-ref lifecycle-ref 0))))
                   (cons "restore"
                         (lambda (state)
                           (vector-set! handler-ref 0 (car state))
                           (vector-set! lifecycle-ref 0 (cadr state))))
                   (cons "install_fork"
                     (lambda ()
                       (let* ((seed (vector-ref seed-ref 0))
                              (fork (_qvr-qiec-get seed "fork_context" #f)))
                         (if (procedure? fork)
                             (let ((clone (fork seed)))
                               (guard (condition
                                        (else
                                          (let ((drop (_qvr-qiec-get clone "on_drop" #f)))
                                            (if (procedure? drop) (drop)))
                                          (raise condition)))
                                 (_qvr-qiec-validate-handler clone manifest))
                               (vector-set! handler-ref 0 clone)
                               (vector-set! lifecycle-ref 0
                                            (_qvr-qiec-lifecycle-enter clone)))))))))
           (grades
             (map (lambda (clause)
                    (cons (_qvr-qiec-get clause "operation")
                          (_qvr-qiec-get clause "grade")))
                  (_qvr-qiec-get manifest "clauses" '())))
           (context
             (list (cons "handler" handler-id)
                   (cons "definition" manifest)
                   (cons "static_arguments" static-arguments)
                   (cons "static" handler-static-environment)
                   (cons "attachments" attachments)
                   (cons "handlers" handlers)
                   (cons "operations" operations)
                   (cons "resumption_uses" 0))))
      (letrec
        ((walk
          (lambda (current)
            (set! current (_qvr-qiec-force current))
            (if (and (eq? (car current) 'effect)
                     (pair? (_qvr-qiec-get (cadr current) "handler_states" '())))
                (for-each
                  (lambda (captured state)
                    (if (eq? captured controller)
                        ((_qvr-qiec-get captured "restore") state)))
                  (_qvr-qiec-get (cadr current) "handler_captures" '())
                  (_qvr-qiec-get (cadr current) "handler_states" '())))
            (let ((handler (vector-ref handler-ref 0)))
              (if (eq? (car current) 'pure)
                  (let* ((value (_qvr-qiec-validate
                                  (_qvr-qiec-get handler "input_validator" #f)
                                  (cadr current)
                                  "handler input type"))
                         (ret (_qvr-qiec-get handler "return" #f))
                         (result (if ret (_qvr-qiec-invoke ret value context) value)))
                    (_qvr-qiec-finalize
                      (_qvr-qiec-validate-computation
                        result (_qvr-qiec-get handler "output_validator" #f)
                        "handler output type")
                      (vector-ref lifecycle-ref 0)))
                  (let* ((request (cadr current))
                         (operation (_qvr-qiec-get request "operation"))
                         (clauses (_qvr-qiec-get handler "operations" '()))
                         (clause (assoc operation clauses))
                         (forward
                           (lambda ()
                             (let ((forwarded-handler (vector-ref handler-ref 0))
                                   (forwarded-lifecycle (vector-ref lifecycle-ref 0))
                                   (forwarded request))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "handler_captures"
                                   (_qvr-qiec-unique
                                     (append (_qvr-qiec-get request "handler_captures" '())
                                             (list controller)))))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "handler_states"
                                   (map (lambda (captured)
                                          ((_qvr-qiec-get captured "capture")))
                                        (_qvr-qiec-get forwarded "handler_captures" '()))))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "lifecycles"
                                   (append (_qvr-qiec-get request "lifecycles" '())
                                           (list (vector-ref lifecycle-ref 0)))))
                               (list 'effect forwarded
                                     (lambda (value)
                                       (vector-set! handler-ref 0 forwarded-handler)
                                       (vector-set! lifecycle-ref 0 forwarded-lifecycle)
                                       (_qvr-qiec-with-ambient
                                         controller
                                         (lambda () (walk ((caddr current) value))))))))))
                    (if (not (equal? (_qvr-qiec-get request "instance") instance))
                        (forward)
                        (begin
                          (if (not (equal? (_qvr-qiec-get request "effect")
                                           (_qvr-qiec-get manifest "effect")))
                              (error 'qiec "QIEC request and installed handler effect disagree"))
                          (if (not clause)
                            (if (or (not (_qvr-qiec-get manifest "total" #f))
                                    (_qvr-qiec-get manifest "forwards_unknown" #f))
                                (forward)
                                (error 'qiec "missing QIEC handler clause" operation))
                            (let* ((uses 0)
                                   (grade-entry (assoc operation grades))
                                   (grade (cdr grade-entry))
                                   (resume
                                     (lambda (value)
                                       (let ((shot uses))
                                         (set! uses (+ uses 1))
                                         (set-cdr!
                                           (assoc "resumption_uses" context)
                                           uses)
                                         (if (equal? grade "0")
                                             (error 'qiec "QIEC zero-grade clause resumed"))
                                         (if (and (or (equal? grade "aff") (equal? grade "1"))
                                                  (> uses 1))
                                             (error 'qiec
                                                    (string-append
                                                      "QIEC resumption exceeds grade "
                                                      grade)))
                                         (if (equal? grade "omega")
                                             (_qvr-qiec-fork-capture request controller shot))
                                         (set! value
                                           (_qvr-qiec-validate
                                             (_qvr-qiec-get (cdr clause) "result_validator" #f)
                                             value "handler operation result type"))
                                         (let ((resumed
                                                 (_qvr-qiec-with-ambient
                                                   controller
                                                   (lambda ()
                                                     (walk (_qvr-qiec-readdress
                                                             ((caddr current) value)
                                                             shot))))))
                                           (if (eq? (car resumed) 'pure)
                                               (cadr resumed)
                                               resumed)))))
                                   (clause-lifecycle
                                     (vector-ref lifecycle-ref 0)))
                              (if (equal? grade "omega")
                                  (_qvr-qiec-validate-capture request controller))
                              (let ((result
                                      (guard (condition
                                               (else
                                                 (_qvr-qiec-drop-request request)
                                                 (_qvr-qiec-lifecycle-drop clause-lifecycle)
                                                 (raise condition)))
                                        (_qvr-qiec-invoke
                                          (cdr clause) request resume context))))
                                (if (and (equal? grade "1") (not (= uses 1)))
                                    (begin
                                      (_qvr-qiec-drop-request request)
                                      (_qvr-qiec-lifecycle-drop clause-lifecycle)
                                      (error 'qiec "QIEC linear clause must resume exactly once")))
                                (if (= uses 0) (_qvr-qiec-drop-request request))
                                (_qvr-qiec-finalize
                                  (_qvr-qiec-validate-computation
                                    result
                                    (_qvr-qiec-get handler "output_validator" #f)
                                    "handler output type")
                                  clause-lifecycle))))))))))))
        (guard (condition
                 (else (_qvr-qiec-lifecycle-drop
                         (vector-ref lifecycle-ref 0))
                       (_qvr-qiec-lifecycle-drop root-lifecycle)
                       (raise condition)))
          (walk (_qvr-qiec-with-ambient controller (lambda () (_qvr-qiec-force (computation))))))))))
(define (_qvr-qiec-run build operations)
  (set! _qvr-qiec-call-serial 0)
  (set! _qvr-qiec-instance-serial 0)
  (let loop ((current (_qvr-qiec-force (build))))
    (if (eq? (car current) 'pure)
        (_qvr-qiec-value (cadr current))
        (let* ((request (cadr current))
               (key (cons (_qvr-qiec-get request "instance")
                          (_qvr-qiec-get request "operation")))
               (flat (assoc key operations))
               (by-instance (assoc (_qvr-qiec-get request "instance") operations))
               (nested (and by-instance
                            (assoc (_qvr-qiec-get request "operation")
                                   (cdr by-instance))))
               (entry (if flat (cdr flat) (and nested (cdr nested)))))
          (if (not entry)
              (error 'qiec "unhandled QIEC operation" key))
          (guard (condition
                   (else (_qvr-qiec-drop-request request) (raise condition)))
            (let ((result (_qvr-qiec-invoke entry request)))
              (loop (_qvr-qiec-force
                      ((caddr current)
                       (_qvr-qiec-validate
                         (_qvr-qiec-get entry "result_validator" #f)
                         result "operation result type"))))))))))
