(define (_qvr-qiec-get container key . rest)
  (let ((entry (and (pair? container) (assoc key container))))
    (if entry (cdr entry) (if (pair? rest) (car rest) #f))))
(define (_qvr-qiec-set container key value)
  (cons (cons key value)
        (filter (lambda (entry) (not (equal? (car entry) key))) container)))
(define (_qvr-qiec-pure value) (list 'pure value))
(define (_qvr-qiec-static-kind argument)
  (let ((kind (_qvr-qiec-get argument "kind" #f)))
    (cond
      ((member kind '("type-variable" "type-application" "function-type" "equality-type")) "type")
      ((member kind '("effect-variable" "effect-ref")) "effect")
      (else "index"))))
(define (_qvr-qiec-static-environment telescope arguments)
  (let ((ordered
          (cond
            ((not arguments) '())
            ((and (pair? arguments) (string? (caar arguments)))
             (map (lambda (binder)
                    (let ((entry (assoc (_qvr-qiec-get binder "name") arguments)))
                      (if entry (cdr entry) (error 'qiec "QIEC static arguments do not match the checked telescope"))))
                  telescope))
            (else arguments))))
    (if (not (= (length ordered) (length telescope)))
        (error 'qiec "QIEC static argument arity does not match the checked telescope"))
    (map (lambda (binder argument)
           (if (not (equal? (_qvr-qiec-static-kind argument)
                            (_qvr-qiec-get binder "kind")))
               (error 'qiec "QIEC static argument kind does not match the checked telescope"))
           (cons (_qvr-qiec-get binder "name") argument))
         telescope ordered)))
(define (_qvr-qiec-alist? value)
  (and (pair? value)
       (for-all (lambda (item) (and (pair? item) (string? (car item)))) value)))
(define (_qvr-qiec-specialize value environment)
  (cond
    ((_qvr-qiec-alist? value)
     (let ((kind (_qvr-qiec-get value "kind" #f))
           (identity (_qvr-qiec-get value "identity" '()))
           (name (_qvr-qiec-get value "name" #f)))
       (if (and (member kind '("type-variable" "index-variable" "effect-variable"))
                (assoc (if (null? identity) name identity) environment))
           (cdr (assoc (if (null? identity) name identity) environment))
           (map (lambda (entry)
                  (cons (car entry) (_qvr-qiec-specialize (cdr entry) environment)))
                value))))
    ((pair? value) (map (lambda (item) (_qvr-qiec-specialize item environment)) value))
    (else value)))
(define _qvr-qiec-ambient-handlers (make-parameter '()))
(define (_qvr-qiec-unique items)
  (let loop ((remaining items) (result '()))
    (if (null? remaining)
        (reverse result)
        (loop (cdr remaining)
              (if (exists (lambda (item) (eq? item (car remaining))) result)
                  result
                  (cons (car remaining) result))))))
(define (_qvr-qiec-with-ambient controller thunk)
  (parameterize ((_qvr-qiec-ambient-handlers
                   (append (_qvr-qiec-ambient-handlers) (list controller))))
    (thunk)))
(define (_qvr-qiec-effect request static-environment)
  (set! request (_qvr-qiec-specialize request static-environment))
  (let ((controllers
          (_qvr-qiec-unique
            (append (_qvr-qiec-get request "handler_captures" '())
                    (_qvr-qiec-ambient-handlers)))))
    (set! request (_qvr-qiec-set request "captures"
                    (_qvr-qiec-get request "captures" '())))
    (set! request (_qvr-qiec-set request "handler_captures" controllers))
    (set! request (_qvr-qiec-set request "handler_states"
                    (map (lambda (controller)
                           ((_qvr-qiec-get controller "capture")))
                         controllers)))
    (list 'effect request _qvr-qiec-pure)))
(define (_qvr-qiec-bind computation continuation . capture-rest)
  (let ((captures (if (pair? capture-rest) (car capture-rest) '())))
    (if (eq? (car computation) 'pure)
        (continuation (cadr computation))
        (let ((request (_qvr-qiec-set
                         (cadr computation)
                         "captures"
                         (append (_qvr-qiec-get (cadr computation) "captures" '()) captures))))
          (list 'effect request
                (lambda (value)
                  (_qvr-qiec-bind ((caddr computation) value) continuation captures)))))))
(define (_qvr-qiec-binding? value)
  (and (pair? value)
       (equal? (_qvr-qiec-get value "qiec" #f) "binding")
       (_qvr-qiec-get value "cell" #f)))
(define (_qvr-qiec-value value)
  (cond
    ((_qvr-qiec-binding? value) (vector-ref (_qvr-qiec-get value "cell") 0))
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "tuple"))
     (_qvr-qiec-get value "items" '()))
    (else value)))
(define (_qvr-qiec-tuple items)
  (list (cons "qiec" "tuple") (cons "items" items)))
(define (_qvr-qiec-constructor constructor static-arguments fields result-type static-environment)
  (list (cons "qiec" "constructor")
        (cons "constructor" constructor)
        (cons "static_arguments" (_qvr-qiec-specialize static-arguments static-environment))
        (cons "fields" fields)
        (cons "result_type" (_qvr-qiec-specialize result-type static-environment))))
(define (_qvr-qiec-evidence evidence static-environment)
  (list (cons "qiec" "evidence")
        (cons "evidence" (_qvr-qiec-specialize evidence static-environment))))
(define (_qvr-qiec-transport evidence value target-type static-environment)
  (_qvr-qiec-specialize evidence static-environment)
  (_qvr-qiec-specialize target-type static-environment)
  value)
(define (_qvr-qiec-attachment attachments attachment expected-type static-environment)
  (let ((entry (assoc attachment attachments)))
    (if (not entry) (error 'qiec "missing QIEC attachment" attachment))
    (let ((binding (cdr entry)))
      (if (or (not (_qvr-qiec-binding? binding))
              (not (assoc "type" binding)))
          (error 'qiec "QIEC attachment must be a typed binding descriptor"))
      (set! expected-type (_qvr-qiec-specialize expected-type static-environment))
      (if (not (equal? (_qvr-qiec-get binding "type") expected-type))
          (error 'qiec "QIEC attachment type disagrees with checked IR"))
      (_qvr-qiec-value
        (_qvr-qiec-validate (_qvr-qiec-get binding "validator" #f)
                            binding
                            (string-append "attachment " attachment))))))
(define (_qvr-qiec-case value branches metadata static-environment)
  (set! metadata (_qvr-qiec-specialize metadata static-environment))
  (if (not (and (pair? value)
                (equal? (_qvr-qiec-get value "qiec" #f) "constructor")))
      (error 'qiec "QIEC case scrutinee is not a constructor value"))
  (let* ((constructor (_qvr-qiec-get value "constructor"))
         (admitted (assoc constructor (_qvr-qiec-get metadata "branches" '())))
         (branch (assoc constructor branches)))
    (if (not admitted) (error 'qiec "constructor is not admitted by the checked QIEC case"))
    (if branch
        (let* ((canonical (_qvr-qiec-get (cdr admitted) "static_arguments" '()))
               (actual (_qvr-qiec-get value "static_arguments" '()))
               (offset (- (length actual) (length canonical))))
          (if (< offset 0)
              (error 'qiec "QIEC constructor static arguments do not match case branch"))
          (let ((branch-environment
                  (append
                    (map (lambda (variable argument)
                           (let ((identity (_qvr-qiec-get variable "identity" '()))
                                 (name (_qvr-qiec-get variable "name" #f)))
                             (if (and (null? identity) (not name))
                                 (error 'qiec "QIEC case branch has an unbindable static variable"))
                             (cons (if (null? identity) name identity) argument)))
                         canonical
                         (list-tail actual offset))
                    static-environment)))
            (apply (cdr branch)
                   (cons branch-environment (_qvr-qiec-get value "fields" '())))))
        (error 'qiec "no QIEC case branch" constructor))))
(define (_qvr-qiec-as-computation value)
  (if (and (pair? value) (or (eq? (car value) 'pure) (eq? (car value) 'effect)))
      value
      (_qvr-qiec-pure value)))
(define (_qvr-qiec-validate validator value label)
  (if (not validator)
      value
      (if (eq? (validator (_qvr-qiec-value value)) #f)
          (error 'qiec "QIEC runtime value failed" label)
          value)))
(define (_qvr-qiec-validate-computation computation validator label)
  (_qvr-qiec-bind
    (_qvr-qiec-as-computation computation)
    (lambda (value) (_qvr-qiec-pure (_qvr-qiec-validate validator value label)))))
(define (_qvr-qiec-capture locals attachment-ids attachments)
  (append
    (map (lambda (entry)
           (let ((binding (cdr entry)))
             (list (cons "kind" "local")
                   (cons "label" (car entry))
                   (cons "binding" binding)
                   (cons "seed"
                         (and (_qvr-qiec-binding? binding)
                              (vector (_qvr-qiec-value binding)))))))
         locals)
    (map (lambda (attachment)
           (let ((entry (assoc attachment attachments)))
             (if (not entry) (error 'qiec "missing QIEC attachment" attachment))
             (let ((binding (cdr entry)))
               (list (cons "kind" "attachment")
                     (cons "label" attachment)
                     (cons "binding" binding)
                     (cons "seed"
                           (and (_qvr-qiec-binding? binding)
                                (vector (_qvr-qiec-value binding))))))))
         attachment-ids)))
(define (_qvr-qiec-duplicable? value)
  (cond
    ((_qvr-qiec-binding? value) (eq? (_qvr-qiec-get value "duplicable" #f) #t))
    ((or (null? value) (boolean? value) (number? value) (string? value)) #t)
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "constructor"))
     (for-all _qvr-qiec-duplicable? (_qvr-qiec-get value "fields" '())))
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "evidence")) #t)
    ((and (pair? value) (equal? (_qvr-qiec-get value "qiec" #f) "tuple"))
     (for-all _qvr-qiec-duplicable? (_qvr-qiec-get value "items" '())))
    (else #f)))
(define (_qvr-qiec-validate-capture request current-handler)
  (for-each
    (lambda (capture)
      (let ((binding (_qvr-qiec-get capture "binding"))
            (label (_qvr-qiec-get capture "label")))
        (if (not (_qvr-qiec-duplicable? binding))
            (error 'qiec "QIEC unrestricted resumption captures nonduplicable value" label))
        (if (and (_qvr-qiec-binding? binding)
                 (_qvr-qiec-get binding "mutable" #f)
                 (not (procedure? (_qvr-qiec-get binding "fork" #f))))
            (error 'qiec "QIEC mutable duplicable binding requires fork" label))))
    (_qvr-qiec-get request "captures" '()))
  (for-each
    (lambda (controller)
      ((_qvr-qiec-get controller "snapshot"))
      (let ((handler ((_qvr-qiec-get controller "get"))))
        (if (not (_qvr-qiec-get handler "duplicable_context" #f))
            (error 'qiec "QIEC unrestricted resumption captures nonduplicable handler context"))
        (if (and (_qvr-qiec-get handler "mutable_context" #f)
                 (not (procedure? (_qvr-qiec-get handler "fork_context" #f))))
            (error 'qiec "QIEC mutable duplicable handler context requires fork_context"))))
    (_qvr-qiec-unique
      (append (_qvr-qiec-get request "handler_captures" '())
              (list current-handler)))))
(define (_qvr-qiec-fork-capture request current-handler shot)
  (begin
        (for-each
          (lambda (capture)
            (let* ((binding (_qvr-qiec-get capture "binding"))
                   (fork (_qvr-qiec-get binding "fork" #f)))
              (if (and (_qvr-qiec-binding? binding) (procedure? fork))
                  (let ((cell (_qvr-qiec-get binding "cell"))
                        (seed (_qvr-qiec-get capture "seed")))
                    (vector-set! cell 0 (fork (vector-ref seed 0)))))))
          (_qvr-qiec-get request "captures" '()))
        (for-each
          (lambda (controller)
            ((_qvr-qiec-get controller "install_fork")))
          (_qvr-qiec-unique
            (append (_qvr-qiec-get request "handler_captures" '())
                    (list current-handler))))))
(define (_qvr-qiec-readdress computation shot)
  (if (eq? (car computation) 'pure)
      computation
      (let* ((request (cadr computation))
             (address (_qvr-qiec-get request "address"))
             (updated (list (car address) (cadr address) (append (caddr address) (list shot))))
             (new-request (_qvr-qiec-set request "address" updated)))
        (list 'effect new-request
              (lambda (value) (_qvr-qiec-readdress ((caddr computation) value) shot))))))
(define (_qvr-qiec-same-members? left right)
  (and (= (length left) (length right))
       (for-all (lambda (item) (member item right)) left)))
(define (_qvr-qiec-validate-handler handler manifest)
  (let ((definition (_qvr-qiec-get handler "definition" #f))
        (structural (map (lambda (clause) (_qvr-qiec-get clause "operation"))
                         (_qvr-qiec-get manifest "clauses" '())))
        (executable (map car (_qvr-qiec-get handler "operations" '()))))
    (if (and definition (not (equal? definition manifest)))
        (error 'qiec "QIEC runtime handler definition disagrees with checked IR"))
    (if (not (_qvr-qiec-same-members? structural executable))
        (error 'qiec "QIEC runtime handler clauses disagree with checked IR"))
    (if (and (procedure? (_qvr-qiec-get handler "fork_context" #f))
             (not (_qvr-qiec-get handler "duplicable_context" #f)))
        (error 'qiec "QIEC handler fork_context requires duplicable_context"))
    (if (and (_qvr-qiec-get handler "mutable_context" #f)
             (_qvr-qiec-get handler "duplicable_context" #f)
             (not (procedure? (_qvr-qiec-get handler "fork_context" #f))))
        (error 'qiec "QIEC mutable duplicable handler requires fork_context"))))
(define (_qvr-qiec-lifecycle handler)
  (list (cons "handler" handler) (cons "finalized" (vector #f))))
(define (_qvr-qiec-lifecycle-exit lifecycle)
  (let ((state (_qvr-qiec-get lifecycle "finalized")))
    (if (not (vector-ref state 0))
        (begin
          (vector-set! state 0 #t)
          (let ((callback
                  (_qvr-qiec-get (_qvr-qiec-get lifecycle "handler")
                                 "on_exit" #f)))
            (if (procedure? callback) (callback)))))))
(define (_qvr-qiec-lifecycle-drop lifecycle)
  (let ((state (_qvr-qiec-get lifecycle "finalized")))
    (if (not (vector-ref state 0))
        (begin
          (vector-set! state 0 #t)
          (let ((callback
                  (_qvr-qiec-get (_qvr-qiec-get lifecycle "handler")
                                 "on_drop" #f)))
            (if (procedure? callback) (callback)))))))
(define (_qvr-qiec-lifecycle-enter handler)
  (let ((lifecycle (_qvr-qiec-lifecycle handler)))
    (guard (condition
             (else (_qvr-qiec-lifecycle-drop lifecycle) (raise condition)))
      (let ((callback (_qvr-qiec-get handler "on_enter" #f)))
        (if (procedure? callback) (callback))))
    lifecycle))
(define (_qvr-qiec-drop-request request)
  (for-each _qvr-qiec-lifecycle-drop
            (_qvr-qiec-get request "lifecycles" '())))
(define (_qvr-qiec-finalize computation lifecycle)
  (let ((current (_qvr-qiec-as-computation computation)))
    (if (eq? (car current) 'pure)
        (begin (_qvr-qiec-lifecycle-exit lifecycle) current)
        (let ((request
                (_qvr-qiec-set
                  (cadr current) "lifecycles"
                  (append (_qvr-qiec-get (cadr current) "lifecycles" '())
                          (list lifecycle)))))
          (list 'effect request
                (lambda (value)
                  (_qvr-qiec-finalize ((caddr current) value) lifecycle)))))))
(define (_qvr-qiec-invoke entry . arguments)
  (apply (if (procedure? entry) entry (_qvr-qiec-get entry "invoke")) arguments))
(define (_qvr-qiec-handle computation instance manifest static-arguments computation-static-environment handlers)
  (set! static-arguments (_qvr-qiec-specialize static-arguments computation-static-environment))
  (let ((handler-static-environment
          (_qvr-qiec-static-environment
            (_qvr-qiec-get manifest "telescope" '()) static-arguments)))
    (set! manifest (_qvr-qiec-specialize manifest handler-static-environment))
    (set! manifest (_qvr-qiec-set manifest "telescope" '())))
  (let* ((handler-id (_qvr-qiec-get manifest "id"))
         (handler-entry (assoc handler-id handlers)))
    (if (not handler-entry) (error 'qiec "missing QIEC handler attachment" handler-id))
    (let* ((prototype (cdr handler-entry))
           (factory (_qvr-qiec-get prototype "context_factory" #f))
           (installed (if (procedure? factory) (factory) prototype))
           (checked
             (begin
               (if (and (eq? installed prototype)
                        (_qvr-qiec-get prototype "mutable_context" #f))
                   (error 'qiec "QIEC mutable handler requires context_factory"))
               (_qvr-qiec-validate-handler installed manifest)
               installed))
           (handler-ref (vector checked))
           (lifecycle-ref (vector (_qvr-qiec-lifecycle-enter checked)))
           (root-lifecycle (vector-ref lifecycle-ref 0))
           (seed-ref (vector checked))
           (controller
             (list (cons "get" (lambda () (vector-ref handler-ref 0)))
                   (cons "seed" (lambda () (vector-ref seed-ref 0)))
                   (cons "snapshot"
                         (lambda ()
                           (vector-set! seed-ref 0 (vector-ref handler-ref 0))))
                   (cons "capture"
                         (lambda ()
                           (list (vector-ref handler-ref 0)
                                 (vector-ref lifecycle-ref 0))))
                   (cons "restore"
                         (lambda (state)
                           (vector-set! handler-ref 0 (car state))
                           (vector-set! lifecycle-ref 0 (cadr state))))
                   (cons "install_fork"
                     (lambda ()
                       (let* ((seed (vector-ref seed-ref 0))
                              (fork (_qvr-qiec-get seed "fork_context" #f)))
                         (if (procedure? fork)
                             (let ((clone (fork seed)))
                               (guard (condition
                                        (else
                                          (let ((drop (_qvr-qiec-get clone "on_drop" #f)))
                                            (if (procedure? drop) (drop)))
                                          (raise condition)))
                                 (_qvr-qiec-validate-handler clone manifest))
                               (vector-set! handler-ref 0 clone)
                               (vector-set! lifecycle-ref 0
                                            (_qvr-qiec-lifecycle-enter clone)))))))))
           (grades
             (map (lambda (clause)
                    (cons (_qvr-qiec-get clause "operation")
                          (_qvr-qiec-get clause "grade")))
                  (_qvr-qiec-get manifest "clauses" '())))
           (context
             (list (cons "handler" handler-id)
                   (cons "definition" manifest)
                   (cons "static_arguments" static-arguments)
                   (cons "resumption_uses" 0))))
      (letrec
        ((walk
          (lambda (current)
            (if (and (eq? (car current) 'effect)
                     (pair? (_qvr-qiec-get (cadr current) "handler_states" '())))
                (for-each
                  (lambda (captured state)
                    (if (eq? captured controller)
                        ((_qvr-qiec-get captured "restore") state)))
                  (_qvr-qiec-get (cadr current) "handler_captures" '())
                  (_qvr-qiec-get (cadr current) "handler_states" '())))
            (let ((handler (vector-ref handler-ref 0)))
              (if (eq? (car current) 'pure)
                  (let* ((value (_qvr-qiec-validate
                                  (_qvr-qiec-get handler "input_validator" #f)
                                  (cadr current)
                                  "handler input type"))
                         (ret (_qvr-qiec-get handler "return" #f))
                         (result (if ret (_qvr-qiec-invoke ret value context) value)))
                    (_qvr-qiec-finalize
                      (_qvr-qiec-validate-computation
                        result (_qvr-qiec-get handler "output_validator" #f)
                        "handler output type")
                      (vector-ref lifecycle-ref 0)))
                  (let* ((request (cadr current))
                         (operation (_qvr-qiec-get request "operation"))
                         (clauses (_qvr-qiec-get handler "operations" '()))
                         (clause (assoc operation clauses))
                         (forward
                           (lambda ()
                             (let ((forwarded-handler (vector-ref handler-ref 0))
                                   (forwarded-lifecycle (vector-ref lifecycle-ref 0))
                                   (forwarded request))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "handler_captures"
                                   (_qvr-qiec-unique
                                     (append (_qvr-qiec-get request "handler_captures" '())
                                             (list controller)))))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "handler_states"
                                   (map (lambda (captured)
                                          ((_qvr-qiec-get captured "capture")))
                                        (_qvr-qiec-get forwarded "handler_captures" '()))))
                               (set! forwarded
                                 (_qvr-qiec-set forwarded "lifecycles"
                                   (append (_qvr-qiec-get request "lifecycles" '())
                                           (list (vector-ref lifecycle-ref 0)))))
                               (list 'effect forwarded
                                     (lambda (value)
                                       (vector-set! handler-ref 0 forwarded-handler)
                                       (vector-set! lifecycle-ref 0 forwarded-lifecycle)
                                       (_qvr-qiec-with-ambient
                                         controller
                                         (lambda () (walk ((caddr current) value))))))))))
                    (if (not (equal? (_qvr-qiec-get request "instance") instance))
                        (forward)
                        (begin
                          (if (not (equal? (_qvr-qiec-get request "effect")
                                           (_qvr-qiec-get manifest "effect")))
                              (error 'qiec "QIEC request and installed handler effect disagree"))
                          (if (not clause)
                            (if (or (not (_qvr-qiec-get manifest "total" #f))
                                    (_qvr-qiec-get manifest "forwards_unknown" #f))
                                (forward)
                                (error 'qiec "missing QIEC handler clause" operation))
                            (let* ((uses 0)
                                   (grade-entry (assoc operation grades))
                                   (grade (cdr grade-entry))
                                   (resume
                                     (lambda (value)
                                       (let ((shot uses))
                                         (set! uses (+ uses 1))
                                         (set-cdr!
                                           (assoc "resumption_uses" context)
                                           uses)
                                         (if (equal? grade "0")
                                             (error 'qiec "QIEC zero-grade clause resumed"))
                                         (if (and (or (equal? grade "aff") (equal? grade "1"))
                                                  (> uses 1))
                                             (error 'qiec
                                                    (string-append
                                                      "QIEC resumption exceeds grade "
                                                      grade)))
                                         (if (equal? grade "omega")
                                             (_qvr-qiec-fork-capture request controller shot))
                                         (set! value
                                           (_qvr-qiec-validate
                                             (_qvr-qiec-get (cdr clause) "result_validator" #f)
                                             value "handler operation result type"))
                                         (let ((resumed
                                                 (_qvr-qiec-with-ambient
                                                   controller
                                                   (lambda ()
                                                     (walk (_qvr-qiec-readdress
                                                             ((caddr current) value)
                                                             shot))))))
                                           (if (eq? (car resumed) 'pure)
                                               (cadr resumed)
                                               resumed)))))
                                   (clause-lifecycle
                                     (vector-ref lifecycle-ref 0)))
                              (if (equal? grade "omega")
                                  (_qvr-qiec-validate-capture request controller))
                              (let ((result
                                      (guard (condition
                                               (else
                                                 (_qvr-qiec-drop-request request)
                                                 (_qvr-qiec-lifecycle-drop clause-lifecycle)
                                                 (raise condition)))
                                        (_qvr-qiec-invoke
                                          (cdr clause) request resume context))))
                                (if (and (equal? grade "1") (not (= uses 1)))
                                    (begin
                                      (_qvr-qiec-drop-request request)
                                      (_qvr-qiec-lifecycle-drop clause-lifecycle)
                                      (error 'qiec "QIEC linear clause must resume exactly once")))
                                (if (= uses 0) (_qvr-qiec-drop-request request))
                                (_qvr-qiec-finalize
                                  (_qvr-qiec-validate-computation
                                    result
                                    (_qvr-qiec-get handler "output_validator" #f)
                                    "handler output type")
                                  clause-lifecycle))))))))))))
        (guard (condition
                 (else (_qvr-qiec-lifecycle-drop
                         (vector-ref lifecycle-ref 0))
                       (_qvr-qiec-lifecycle-drop root-lifecycle)
                       (raise condition)))
          (walk (_qvr-qiec-with-ambient controller computation)))))))
(define (_qvr-qiec-run computation operations)
  (let loop ((current computation))
    (if (eq? (car current) 'pure)
        (_qvr-qiec-value (cadr current))
        (let* ((request (cadr current))
               (key (cons (_qvr-qiec-get request "instance")
                          (_qvr-qiec-get request "operation")))
               (flat (assoc key operations))
               (by-instance (assoc (_qvr-qiec-get request "instance") operations))
               (nested (and by-instance
                            (assoc (_qvr-qiec-get request "operation")
                                   (cdr by-instance))))
               (entry (if flat (cdr flat) (and nested (cdr nested)))))
          (if (not entry)
              (error 'qiec "unhandled QIEC operation" key))
          (guard (condition
                   (else (_qvr-qiec-drop-request request) (raise condition)))
            (let ((result (_qvr-qiec-invoke entry request)))
              (loop ((caddr current)
                     (_qvr-qiec-validate
                       (_qvr-qiec-get entry "result_validator" #f)
                       result "operation result type")))))))))
