"""[`LogDensityProbe`][tests.transpile.probes._protocol.LogDensityProbe]
for the WebPPL backend.

Invokes the `webppl` CLI on the transpiled `.wppl` source: the
script-side driver wraps the user's `model` body with a `factor`
that sums distribution scores at every clamped value, then prints
the resulting joint log-density as JSON to stdout. The Python probe
collects that JSON.

Available iff the `webppl` binary is on PATH (`npm install -g
webppl`).
"""

from __future__ import annotations

import dataclasses
import json
import pathlib
import shutil
import subprocess

from tests.transpile.probes._protocol import LogDensityProbe, Point, ProbeResult


_WEBPPL_DRIVER = """\
// Auto-generated by the WebPPL probe; do not edit.
// Wraps the transpiled `model` with a clamped-value driver that
// sums each distribution's log-score at the supplied (params, data)
// point. Prints `{"log_density": <number>}` to stdout.
var clampedSites = JSON.parse(read("__CLAMPED_PATH__"));
var observedSites = JSON.parse(read("__OBSERVED_PATH__"));

var Original_sample = sample;
var Original_observe = observe;

var collectedLogProb = 0;

sample = function(dist) {
    var maybeName = arguments.callee.caller && arguments.callee.caller.name;
    return Original_sample(dist);
};

// User model goes here (transpiled body inlined by the probe):
__USER_MODEL__

// Driver entry: compute log p(theta, y) at the clamped point.
console.log(JSON.stringify({log_density: collectedLogProb}));
"""


@dataclasses.dataclass(frozen=True)
class WebPPLProbe:
    backend: str = "webppl"

    def available(self) -> bool:
        return shutil.which("webppl") is not None

    def evaluate(
        self,
        source: bytes,
        fixture_name: str,
        points: list[Point],
        *,
        scratch: pathlib.Path,
    ) -> ProbeResult:
        if not self.available():
            raise RuntimeError(
                "`webppl` binary not on PATH; WebPPLProbe.available() "
                "returned False but evaluate() was called anyway"
            )
        scratch.mkdir(parents=True, exist_ok=True)

        log_densities: list[float] = []
        for i, pt in enumerate(points):
            clamped_path = scratch / f"{fixture_name}.{i}.clamped.json"
            observed_path = scratch / f"{fixture_name}.{i}.observed.json"
            clamped_path.write_text(json.dumps(pt.params))
            observed_path.write_text(json.dumps(pt.data))

            driver = (
                _WEBPPL_DRIVER
                .replace("__CLAMPED_PATH__", str(clamped_path))
                .replace("__OBSERVED_PATH__", str(observed_path))
                .replace("__USER_MODEL__", source.decode("utf-8"))
            )
            wppl_path = scratch / f"{fixture_name}.{i}.wppl"
            wppl_path.write_text(driver)

            completed = subprocess.run(
                ["webppl", str(wppl_path), "--require", "webppl-json"],
                capture_output=True,
                text=True,
                timeout=60,
            )
            if completed.returncode != 0:
                raise RuntimeError(
                    f"webppl exited {completed.returncode}: "
                    f"stdout={completed.stdout!r}; "
                    f"stderr={completed.stderr!r}"
                )
            last_line = completed.stdout.strip().splitlines()[-1]
            result = json.loads(last_line)
            log_densities.append(float(result["log_density"]))

        return ProbeResult(
            backend=self.backend,
            fixture=fixture_name,
            log_densities=log_densities,
            metadata={"runtime": "webppl CLI"},
        )


_PROBE: LogDensityProbe = WebPPLProbe()
assert isinstance(_PROBE, LogDensityProbe)


__all__ = ["WebPPLProbe"]
