"""Sync ``grammars/qvr/src/grammar.json`` into the package data
location ``src/quivers/dsl/_grammar_data/grammar.json`` so the wheel
ships the file alongside the Python sources.

``_grammar_introspection._grammar_json_path()`` reads from the
package-local copy at runtime. The canonical source remains
``grammars/qvr/src/grammar.json`` (regenerated by
``tree-sitter generate``); this script keeps the wheel-shipped
copy in lockstep with that canonical source.

Run before every build. CI gates the wheel build on this script
having been run by diffing the two files.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_SRC = _ROOT / "grammars" / "qvr" / "src" / "grammar.json"
_DST = _ROOT / "src" / "quivers" / "dsl" / "_grammar_data" / "grammar.json"


def main(argv: list[str] | None = None) -> int:
    argv = argv or sys.argv[1:]
    if "--check" in argv:
        if not _DST.is_file():
            print(f"missing: {_DST}", file=sys.stderr)
            return 1
        if _SRC.read_bytes() != _DST.read_bytes():
            print(
                f"out of sync: {_DST} differs from {_SRC}; "
                f"run ``python tools/sync_grammar_data.py``",
                file=sys.stderr,
            )
            return 1
        return 0
    _DST.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(_SRC, _DST)
    print(f"synced {_DST.relative_to(_ROOT)} from {_SRC.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
